### ISSUE TITLE
Account verifizieren geht nicht

### ISSUE THREAD

**Issue by wr2champ** [Deazl/pr0keys#1]
Ich bekomme keinen Code und soll 15 Minuten warten. Das ganze dauert nun schon fast eine Stunde an.

**Comment by mist** [comment]
+1 gleiches Problem

**Comment by TesTaL0rch** [comment]
same here
Aber ich vermute mal, dass es jetzt auch wieder zu Überlastungen kommt, da es einfach alle gleichzeitig versuchen. Ich werde 3-4h warten und empfehle euch, das gleiche zu tun.. vllt. schau ich sogar erst heut Abend wieder rein, ob's funzt.

**Comment by Deazl** [comment]
Da zu dem Zeitpunkt dieser Antwort 403 User versuchen an ihren Code zu kommen, die PN Grenze pro Stunde aber irgendwo im 50er Bereich befindet, wird das ganze derzeit schwierig zu lösen sein.

Ich versuche bereits mit den Admins deswegen Kontakt aufzunehmen.

**Comment by Biskit1943** [comment]
Da hilft nur mehr Benis ¯\_(ツ)_/¯

**Comment by Deazl** [comment]
@Biskit1943 Nein. Der Benis wird erst geprüft nachdem man sich verifiziert hat.
Von der Registrierung wird niemand ausgeschlossen.

**Comment by Xiphias1337** [comment]
Selbes Problem... dann muss man wohl warten

**Comment by schr3j** [comment]
Da das hier mehr oder weniger das gleiche Thema wie #2 ist würde ich den hier schließen. Im anderen Issue wird das Ganze ja schon lösungsorientierter besprochen...

**Comment by Deazl** [comment]
@schr3j Ich dachte ich hätte den geschlossen. danke.
