### ISSUE TITLE
Website "down"?

### ISSUE THREAD

**Issue by xlaum** [Deazl/pr0keys#10]
Die Website sah grad so aus: https://i.gyazo.com/fcd86487774ea6b2dac4b3395aaef96a.png

Jetzt bekomm ich  "Whoops, looks like something went wrong"

**Comment by ghacproductions** [comment]
Probiers bitte jetzt noch einmal, bei mir klappt es einwandfrei.

**Comment by Deazl** [comment]
Eben das Update für gepusht. Nun funktioniert wieder alles wie gewohnt, inklusive der Prüfung ob du einen Key bekommen kannst oder nicht :)

**Comment by xlaum** [comment]
Vielen Dank!
