### ISSUE TITLE
Einloggen nicht möglich. Gebannt?

### ISSUE THREAD

**Issue by BoboElHrsn** [Deazl/pr0keys#105]
Hey,

wenn ich versuche mich einzuloggen erhalte ich die Nachricht
"pages.auth.messages.banned"

Account: BoboElHurensohn

Hat noch jemand das Problem?
Wüsste nicht, warum ich gebannt sein sollte ^^

**Comment by Deazl** [comment]
Dein Account wurde von mir gesperrt, da der Verdacht besteht, dass du mit mehreren Accounts arbeitest um dir selbst einen Vorteil zu beschaffen. Ich habe das ganze einige Zeit beobachtet und vor kurzem nun entschieden.

**Comment by BoboElHrsn** [comment]
Habe doch schon länger nichts mehr angeboten, wie kann das sein?
Das Einzige was ich in letzter Zeit gemacht habe ist ein paar Keys zu claimen, die mir noch gefehlt haben. Wie kommt da der Verdacht auf Multi-Accounting auf?

**Comment by Deazl** [comment]
Über die genauen Abläufe der Prüfung bzw. woran das fest gemacht wird gebe ich keine Informationen, da diese von anderen verwendet werden könnten um dies zu umgehen. Tut mir leid.

**Comment by BoboElHrsn** [comment]
Wäre nett. Man sollte nicht Angst haben gebannt zu werden, wenn man Keys claimt.

**Comment by Deazl** [comment]
Wird man auch nicht. Wenn man jedoch mehrere zig Keys von ein und dem selben User in einem kurzen Zeitraum hintereinander (bei dir 17) claimed ist das schon auffällig.

**Comment by BoboElHrsn** [comment]
Danke dir.
