### ISSUE TITLE
Freischaltcode Errors

### ISSUE THREAD

**Issue by Biskit1943** [Deazl/pr0keys#11]
Also ich Probiere jetzt schon den ganzen Tag mir den Code senden zu lassen, anfangs kam irgend ein Fehler, dann das das Pr0 nicht kann, dann ein 404 und zuletzt kamm ein 500 Error. Liegts an mir oder was anderem?

Edit: Ach ja es kammt nach jedem Error 15 min warten also Danke Merkel!

**Comment by Deazl** [comment]
Wie heißt du denn im pr0gramm? Dann kann ich für dich nachschauen und dir den Code zusenden.

**Comment by NekNekx** [comment]
Versuche es auch schon den ganzen tag username "NekNek" T__T

**Comment by DreamSupreeeme** [comment]
Hab das gleiche problem.

**Comment by DerjenigeWelche** [comment]
Ich auch.
Pr0gramm Name: ChilleMiller

**Comment by Gamewalker** [comment]
Kommt der Code eigentlich noch? Würde gerne in die Registrierung schauen, geht mir total auf den Sack das ich seit Stunden nur Fehler kriege und jedes mal nach 15 Minuten ein neuer Fehler kommt :P

**Comment by Biskit1943** [comment]
http://pr0gramm.com/user/Mas0n

**Comment by gw23** [comment]
Funktioniert bei mir leider auch nicht.  Will mir den Codes zusenden dann lädt mein Browser ewig und wenn ich dann ohne das etwas passiert ist noch mal auf Code zusenden drücke bekomm ich die Nachricht das es nur alle 15 min geht. Name : gw2

**Comment by Cuber006** [comment]
Bei mir das selbe Problem
Name: Cuber006

**Comment by Biskit1943** [comment]
Bei mir gehts jetzt

**Comment by SoulAce1280** [comment]
Bei mir leider noch immer nicht.

http://pr0gramm.com/user/SoulAce1280

Danke.

**Comment by Manu795** [comment]
Servus, 
bei mir leider ebenfalls der gleiche Fehler. 
[https://pr0gramm.com/user/Manu7](url)
Vielen Dank schonmal!

**Comment by Biskit1943** [comment]
@Manu795 Steht bei dir ein Error oder das das Pr0 beschäftigt ist, falls es letzteres ist warte einfach mal

**Comment by Manu795** [comment]
Ich hatte nach gestrigen Registrieren keinen Freischaltcode erhalten, beim Klick für das erneute Senden des Codes habe ich mehrmals einen Timeout bekommen. 
Beim zweiten Versuch für heute, hat es allerdings plötzlich funktioniert. Danke!

**Comment by SoulAce1280** [comment]
Ich versuche es seit gestern Mittag.
Gestern war der Fehler 403. Trotz der 15min. Timeout ging es danach leider
immer noch nicht. 5-6 mal versucht.

Heute ist es Fehler 500

Grüße


Am 16. Februar 2016 um 12:27 schrieb Manu795 <notifications@github.com>:

**Comment by 17leo06** [comment]
Ja ich habe genau das selbe Problem. Am Anfang konnte ich mich normal registrieren und habe auch meinen Freischaltcode vom Bot bekommen. Nach dem Reset allerdings versuche ich seit zwei Tagen den Freischaltcode zu erhalten. Passieren tut jedoch nichts. Ich wäre ebenfalls für eine manuelle Zusendung des Codes dankbar. 
http://pr0gramm.com/user/17leo06
