### ISSUE TITLE
Keine Keys erhalten, die man selbst geteilt hat

### ISSUE THREAD

**Issue by Rasibobs** [Deazl/pr0keys#13]
Keys, die der User selbst geteilt hat, sollten ihm nicht vorgeschlagen werden.

**Comment by Deazl** [comment]
Solch eine Abfrage wird im nächsten Update kommen.

**Comment by NbdY83** [comment]
Habe einen Eingereichten Key vorgeschlagen bekommen. Bug ist also noch/wieder vorhanden

**Comment by Deazl** [comment]
Das "Problem" wurde bisher nie behoben. Ist eine kleine Anpassung. Ich schau was ich auf die schnelle tun kann.
