### ISSUE TITLE
Spiel nicht gefunden

### ISSUE THREAD

**Issue by Biskit1943** [Deazl/pr0keys#14]
**Two Worlds 2** wird nicht vom System als Spiel erkannt

**Comment by Quadratball** [comment]
Dead Space 3 / Populous auch nicht.

Wäre auch dafür dass man unbekannte Spiele hinzufügen kann, diese haben dann eben kein Bild oder ja nach Mühe/Aufwand kann man selber ein Bild hinzufügen.

**Comment by ashyda** [comment]
Battlefield 3 gibts auch nicht.

**Comment by Biskit1943** [comment]
Ich glaube die Datenbank besteht bisher nur aus dem üblichen Random Key shit

**Comment by Vaess** [comment]
Die Seite greift auf die Steam Datenbank zu. Dementsprechend finden sich auch nur Games die es auf Steam gibt.
Two Worlds II existiert
The Sims™ 3 existiert
Populous gibts auf Steam nicht
Dead Space 3 ist glaub ich Origin only

**Comment by Biskit1943** [comment]
Man muss die 2 als II schreiben... ist ja behindert

**Comment by Quadratball** [comment]
Sonderzeichen beachten! wollte z.B. Rayman Origins einreichen dabei muss man aber "Rayman® Origins" schreiben weil er sonst das ® vermisst.

**Comment by roebert** [comment]
es reicht aus Rayman zu schreiben und dann in die Auto-Complete-Liste zu schauen
Mit der Plattform-Auswahl-Box vor Key-Eingabe wäre es pr0keys auch einfacher nach dem Spiel zu suchen - wenn man Steam auswählt, wird bei Steam gesucht, wählt man ubi aus wird dort gesucht ?!

**Comment by Blizzer92** [comment]
Für den nächsten Patch ist eine Auswahl zwischen Steam/Origin und anderen geplant.
