### ISSUE TITLE
Lieber Liste als Random-Keys

### ISSUE THREAD

**Issue by eltomato89** [Deazl/pr0keys#16]
Die Idee mit dem Random Key finde ich nich so geil.
Von aktuell rund 25 Keys, sind 10 von mir .. 

Wie wäre es denn wenn man ne Art Benis einführt, (Geteilte Keys minus eingelöste Keys) und ab nem positiven Benis eine Liste aller verfügbaren Spiele sieht. Dann kann man sich da einen raussuchen.

Grade bei Humble Bundles werden viele Keys doppelt und dreifach im System liegen.

(Die Ein-Key-Pr0-Tag-Regel finde ich übrigens gut!)

**Comment by Blizzer92** [comment]
Wir werden deinen Vorschlag im Team besprechen.

**Comment by Deazl** [comment]
Wir haben das ganze besprochen und sind zu dem Entschluss gekommen, dass der User eine Liste von 5 hochwertigeren Spielen (gemessen an Metacritic) zur Verfügung gestellt bekommt, welche er einmal neu laden kann, womit ihm insgesamt 10 Spiele angeboten werden. Man erhält dieses Privileg ab einer bestimmten Anzahl funktionierender eingereichter Keys, welches einem auch wieder entzogen werden kann, wenn falsche Keys eingereicht werden.

Über eine Umsetzung einer Art "Benis" wird weiterhin diskutiert.

**Comment by scmbb** [comment]
Praktisch wäre das vielleicht so:

Benis = Eingereichte Keys - Eingelöste Keys
Wenn man im Plus ist, kann man sich 1x alle 24h alle Keys anschauen, deren Wert auf Steam <= Benis ist. Danach landet man wie alle anderen im Randomsystem.
Alle mit 0 oder Minusbenis bleiben ausschliesslich bei dem Randomsystem und können auch mal Glück haben.

**Comment by TesTaL0rch** [comment]
Also ich muss erstma sagen: ich finde die ganze Aktion echt nice! Selbst bin ich nicht so der große Spielekäufer und hab auch keine Freunde, die mal keys übrig haben, weshalb free-keys mir bislang immer verwährt blieben. Und wenn mal keys im Forum gepostet wurden, waren die eigtl. immer gleich weg, selbst wenn man es einmal gleich mitbekommen haben sollte. Von daher top (insbesondere die 24h-1key-Regel)!
Jetzt eine kleine Anmerkung. Wenn die Leute, die tausende zusätzliche keys übrig haben, hier auch die besten Spiele abgreifen können (zwecks Benis-Idee) dann bleibt für den kleinen Typ, der sich super freut auch mal einen key geschenkt zu bekommen, bestimmt eher der "Bodensatz" der Spiele übrig.
Auf pr0 find ich den Benis alles in allem ne sinnvolle Sache (mal von p0rn- & minus-content-spam abgesehen) - auch da sich hier bei den keys nur "wertvolle" pr0-Mitglieder beteiligen können. 
Was eure Idee angeht, verstehe ich das jetzt so: wer viel Kohle investiert, massenhaft Spiele kauft und viele Zusatz-keys kriegt & hier teilt, der kriegt die besten Spiele ab und Leute die weniger Geld haben (um mind. 1 überzähligen key/Tag zu spenden und so hier nen positiven Benis zu kriegen) müssen halt sehen was übrig bleibt. 
Allerdings besteht halt auch die Frage nach der Fairness und ob die Leute, die viel beitragen, dafür nicht auch ne Belohnung verdienen.. ich finde halt einfach den kapitalistischen/kommerziellen Gedanken daran etwas schade. Da ich aber selbst kein wertvoller key-Spender bin und mich auch mit humblebundle und dem ganzen Zeug nich auskenne, muss ich die Beurteilung davon anderen überlassen - wollte den Gedanken jetzt nur einmal in den Raum werfen.
