### ISSUE TITLE
Steam fremde Keys?

### ISSUE THREAD

**Issue by eltomato89** [Deazl/pr0keys#17]
Origin keys und bspw. Uploaded.to Keys wären noch Sinnvoll. 

Grade weil jeder bei Uploaded nen 48h Gäste-Pass dazu bekommt.

**Comment by roebert** [comment]
siehe https://github.com/Deazl/pr0keys/issues/7
andere Plattformen neben Steam sind in Arbeit

**Comment by Blizzer92** [comment]
Beim nächsten Patch wird es eine Auswahlmöglichkeit zwischen verschiedenen Anbieter geben.

**Comment by therealshark** [comment]
HumbleBundle giftlinks wären auch noch klasse. Hab da einiges rumliegen, aber direkt die Keys verteilen kann wohl zu Problemen führen.
