### ISSUE TITLE
verbessertes Auto-Complete bei Spielsuche

### ISSUE THREAD

**Issue by roebert** [Deazl/pr0keys#18]
Ich erlebe es immer wieder, dass Eingaben nicht ankommen - schaut so aus, als ob Du selber die Auto-Complete-Funktion geschrieben hast. Meiner Meinung nach nicht ganz optimal. Geschriebenes landet hier oft in /dev/null, da Timeout und ajax-Request das input-Feld für einen kurzen Moment auf readonly stellen.

**Comment by Deazl** [comment]
Ich konnte ein derartiges Problem noch nicht feststellen.
Welchen Brauser (+ Version) nutzt du? Tritt dieser Fehler nur unter bestimmten Vorraussetzungen auf bzw. ist dieser reproduzierbar?

**Comment by roebert** [comment]
tritt an allen browsern auf, die ich probiert habe (chrome auf mac/pc, bb10-browser, firefox auf pc)
lässt sich reproduzieren:
fange an zu schreiben, warte eine halbe sekunde und schreibe weiter - die eingabe kommt nicht an, weil das input-feld auf readonly gestellt ist - diese halbe sekunde(+dauer vom ajax-request) ist dann auch circa die Zeit in der man sich wundert warum die Eingabe nicht ankommt und erneut die Tastatur betätigt und es kommt wieder nichts an.
