### ISSUE TITLE
Möglichkeit für user unter 1000 Benis keys hinzuzufügen.

### ISSUE THREAD

**Issue by hex16de** [Deazl/pr0keys#19]
Es sollte auch für user unter 1000 Benis die möglichkeit geben keys hinzuzufügen. Ebenso sollte es die möglichkeit geben anonym keys zu spenden (Angemeldet sollte man dafür aber schon sein, sonst gibt es wieder einige spammer.)

**Comment by Quadratball** [comment]
Darf ich raten, du bist ne Fliese?
ich finde es eigentlich relativ gut dass man 1000 braucht, das ist nicht zu viel aber auch genug damit keine Fliesen und inaktive User was bekommen.
Ehr finde ich eine Funktion gut bei der man sich **quasi** für Keys Benis kaufen kann.

Also als Beispiel:
du hast 700 Benis auf Pr0, dann spendest du einen Key und hast dann auf der Key-Seite für den Key +300 bekommen und somit 1000.

**Comment by hex16de** [comment]
Also erstens. Ich bin keine Fliese.... zweitens: Was würde es mir bringen wenn jemand mit unter 1000 Benis euch keys zur verfügung stellt!?

**Comment by Deazl** [comment]
Ladies, kriegt euch ein.
Für einige Ausnahmen ist das geplant. Ausnahmen können später beantragt werden.
