### ISSUE TITLE
Code sending verifying 

### ISSUE THREAD

**Issue by hrkrx** [Deazl/pr0keys#2]
um die Last bei der Verifizierung zu sparen, kannst du das nicht auf einen anderen Server auslagern? würde sogar einen zur Verfügung stellen.

**Comment by Deazl** [comment]
Die Last ist nicht das Problem. Das pr0gramm begrenzt die Anzahl der PNs pro Stunde. Das ist auch das, was die Ladezeiten so in die Höhe treibt. Ich bin dabei das ganze Asynchron zu gestalten.
An einfachen Aufrufen der Website kann der Server locker um die 1000 mehr pro Sekunde vertragen. Dafür ist er da ;)

**Comment by stroskler** [comment]
bekomme einen Serverfehler 500 bei deinem resend button

**Comment by hrkrx** [comment]
@Deazl wie wäre es mit ner queue die die Nachrichten rausschickt, sobald es geht, damit nicht jeder idiot die ganze Zeit F5 drückt und damit die nächtlichen Stunden auch ausgenutzt werden können in denen sich nicht unbedingt jemand registriert

**Comment by stroskler** [comment]
@hrkrx es ist eine queue vorhanden man muss 15min warten

**Comment by Deazl** [comment]
@stroskler 
Sobald ich Zeit habe den Fehler suchen, werde ich ihn finden und das Problem beheben.
Das was du meist ist lediglich ein Timer, keine Queue. Eine Queue ist quasi eine Liste aller Nachrichten die gesendert werden müssen. Sobald nachrichten gesendet werden können, wird diese Aufgabe aus der Liste entfernt.

@hrkrx 
Eine Queue wollte ich ohnehin schon umsetzen. Sofern du PHP und Laravel kannst, kannst du mir gerne helfen, nachdem das Projekt hier in der Repo liegt ;)

**Comment by hrkrx** [comment]
dealz ich bin mir jetzt nicht ganz sicher ob ich dich richtig verstanden habe, bzw. du mich. Aber ich formuliere das ganze mal als Frage: Wenn ich auf meinen Code warte, wird der dann rausgeschickt wenn ich im richtigen moment _resend_ drücke oder irgendwann wenn ich dran bin und die Messages pro Stunde noch nicht erreicht sind?

**Comment by Deazl** [comment]
@hrkrx Es wird versucht sofort ein Request zu erstellen und die Nachricht zu senden. Genau ist das ist das Problem. Deswegen möchte ich auf eine Queue ausweichen: https://laravel.com/docs/5.2/queues

**Comment by stroskler** [comment]
@Deazl ja okay ich weiß was du meinst :) Zum Thema beitragen könnte ich höchstens an resourcen oder java

**Comment by Gamewalker** [comment]
SChonmal Gamb kontaktiert ob er das Limit bei deinem User erhöhen kann oder ob du ggf 2-3  User nutzen kannst?

**Comment by Deazl** [comment]
@Gamewalker 
Jup. Hab das Team bereits 3x kontaktiert.

**Comment by Nodebuck** [comment]
Wäre es nicht sinnvoller, wenn man einen Key bekommt und diesen dann an den Bot per PN schickt? 

Dann gibt es kein Problem mit dem Rate Limit.

**Comment by Deazl** [comment]
Sowas habe ich bereits überlegt, war mir bisher jedoch nicht sicher wie genau man das umsetzen könnte.

**Comment by Nodebuck** [comment]
Jeder Account hat einen einzigartigen Key, mit dem die pr0gramm-Verknüpfung verifiziert werden kann. Den schickt man den Bot und dieser geht die PNs durch und sucht nach den Keys - der kann ja ruhig jede Minute oder halbe Minute fetchen, da gibt es keine so starke Begrenzung.

**Comment by Nodebuck** [comment]
Ist ja eigentlich das ganze einfach nur umgekehrt.

**Comment by hrkrx** [comment]
@Deazl Nodebucks Idee ist gut mMn. Sollte auch nicht so schwierig sein, dass umzusetzen, ABER dann hat man auf jeden Fall wartezeit, da man nicht dauernd die Nachrichten abfragen kann/sollte

**Comment by schr3j** [comment]
Naja so einmal pro Minute oder alle 30s wäre jetzt ja nicht so belastend für das pr0. Und lieber eine Minute als Stunden warten oder nicht?

**Comment by Deazl** [comment]
Die Idee ist wirklich nicht schlecht. Wir werden auch sicher darauf zurück greifen, wenn Gamb das Limit nicht raus nimmt.

Man könnte locker alle 15 Sekunden abfragen. Da gibts kein Limit.
Hab vorhin auch schon problemlos 502 User in 6,2 Sekunden gefetched. Ist also nicht das Problem.

**Comment by schr3j** [comment]
Noch besser wäre vielleicht eine automatische Abfrage alle Minute (oder seltener) und einen refresh button bei nicht bestätigten Accounts mit dem das Nachrichten fetchen manuell ausgelöst werden kann. Dann soll man halt eine Nachricht an den Bot schicken, danach den Button anklicken und muss nicht warten. Eventuell dann noch einen Filter einbauen das maximal alle 5s abgefragt wird denn es werden ja sowieso alle Nachrichten geladen nehme ich an, da muss das dann nicht für jeden User einzeln sein.

**Comment by Deazl** [comment]
Über den `/inbox/unread`Endpoint kann man sich auch nur die ungelesenen Nachrichten abrufen, so by the way als Info. Würde einiges ersparen.
