### ISSUE TITLE
User Links verweisen auf /user/System

### ISSUE THREAD

**Issue by AR321** [Deazl/pr0keys#21]
Unter "Geteilte Keys" Spalte "Eingelöst" wird bei reservierten Keys beim klick auf den Usernamen immer nach pr0.com/user/System verwiesen

**Comment by Deazl** [comment]
Wird gefixxt, danke!

**Comment by Deazl** [comment]
Bug ist behoben worden. Der Hotfix wurde soeben veröffentlicht.
