### ISSUE TITLE
Reservierte Keys

### ISSUE THREAD

**Issue by AR321** [Deazl/pr0keys#22]
Wäre es nicht sinnvoll wenn reservierte Keys nach einer gewissen Zeitspanne (10/15 Minuten) wieder freigegeben würden, bei mir ist momentan die Hälfte der gespendeten Keys auf reserviert.

**Comment by ErenJaeger69** [comment]
Es wird so weit ich weiß, nach 24h wieder freigegeben..

**Comment by Deazl** [comment]
Nein, derzeit werden sie nicht wieder freigegeben.

**Comment by AR321** [comment]
Ein dritter Button neben "Key akzeptieren" und "Neuen Key erhalten" wäre noch gut, sowas wie "Später nochmal kommen" wenn nichts dabei war was einem gefällt und man wann anders eben nochmal durschauen möchte.

**Comment by Deazl** [comment]
Inzwischen werden sie etwa 30 Minuten nach einer Reservierung wieder freigegeben.
Damit ist auch ein von dir genannter dritter Button nicht ehr von Nöten.
