### ISSUE TITLE
Ungültiger Produktschlüssel

### ISSUE THREAD

**Issue by Jauwa** [Deazl/pr0keys#23]
Moin, habe einen Key bekommen der nicht auf Steam einlösbar ist. Gibt es jetzt schon Keys von anderen Plattformen ? Wenn ja würde ich diesen gerne wieder zurückschmeißen. Geht jedoch nicht da er schon einmal auf der Seite "geteilt" wurde.

**Comment by Deazl** [comment]
Kein Thema. Wie heißt du auf pr0gramm? Dann kann ich den Key wieder zurück in die Trommel werfen.

**Comment by Jauwa** [comment]
Genau wie hier. Soll ich den Key an pornl0ader oder prokeys schicken ?

**Comment by Deazl** [comment]
Ich nehme an es handelt sich um den Key 2WP-... von heute ~20 Uhr?

**Comment by Jauwa** [comment]
Richtig.

**Comment by Deazl** [comment]
Dabei handelt es sich um einen Uplay Key für Might & Magic: Heroes VI. Soll ich den zurück in die Trommel werfen? Wenn damit dann jedoch was nicht stimmt, geht das erstmal auf deine Kappe, da du ihn zuletzt zu Gesicht bekommen hast. Gerne kannst du bei einem weiteren Gespräch (Sofern Probleme entstehen) an den eigentlichen Autor weiterleiten.

**Comment by Jauwa** [comment]
Ja, würde ihn gerne zurückgeben.

**Comment by Deazl** [comment]
Ist erledigt.
