### ISSUE TITLE
Keinen "richtigen" Key erhalten

### ISSUE THREAD

**Issue by Rasibobs** [Deazl/pr0keys#24]
![image](https://cloud.githubusercontent.com/assets/17267604/13104176/d53ae628-d55b-11e5-9586-8c6bcbcb5850.png)

**Comment by Deazl** [comment]
Das ist richtig, leider ein wenig unglücklich gelaufen. Manchmal kann es passieren, dass ich am Livesystem testen muss. Der Key ist mittlerweile wieder aus der Datenbank verschwunden.
