### ISSUE TITLE
Session expires VS 'Angemeldet bleiben'

### ISSUE THREAD

**Issue by roebert** [Deazl/pr0keys#26]
Die Checkbox 'Angemeldet bleiben' beim Login auf der Seite hat keinerlei Effekt. Die Session ist - egal was man auswählt - auf eine Stunde begrenzt. Die laravel_session ist gültig bis Zeitpunkt des Logins+1h.

**Comment by Deazl** [comment]
Der Bug wurde in der aktuellen Version behoben. Danke!

**Comment by Nova900** [comment]
Scheint nicht behoben zu sein - ich muss mich trotzdem immer wieder neu einloggen, obwohl ich das Kästchen aktivieren.
