### ISSUE TITLE
Vorschlag: Game Titel verlinken

### ISSUE THREAD

**Issue by roebert** [Deazl/pr0keys#27]
Ein Vorschlag: habe heute wieder einen Key abholen dürfen (Danke!) - das sieht schon viel besser aus! Für den Nutzer wäre es natürlich noch bequemer wenn der Titel des Spiels als Link (auf z.B. die Spielebeschreibung bei Steam) gerendert wird. Bei einem Titel, den man bis dato nicht kannte, kann man so recht schnell ohne zu googlen beurteilen ob man den key einlöst oder nicht.

**Comment by Deazl** [comment]
Vielen Dank, wird im nächsten Update in spätestens einer Stunde implementiert.

**Comment by Deazl** [comment]
Nach einigen Hürden ist nun auch das Update hierfür draußen.

**Comment by roebert** [comment]
Titel ist nur verlinkt wenn man den Key schon bezogen hat - wenn man den Key angeboten bekommt leider noch nicht.
