### ISSUE TITLE
Vorschlag: Key ablehnen

### ISSUE THREAD

**Issue by scmbb** [Deazl/pr0keys#28]
Kurzer Vorschlag:

Ich fände es gut wenn man den zugeteilten Key entweder annehmen oder permanent ablehnen kann. Dadurch wird verhindert, dass nur die Rosinen rausgepickt werden weil man immer und immer wieder durch die aktuellen Keys scrollen kann.

**Comment by Deazl** [comment]
Etwas derartiges steht bereits auf der ToDo.

**Comment by Roffelchen** [comment]
Bin ich auf jeden Fall dafür, habe gestern keinen Key bekommen, weil ich beim ablehnen 2 mal den selben Key vorgeschlagen bekommen habe, von einem Spiel das ich schon besitze.

**Comment by Deazl** [comment]
Das passiert dann, wenn es mehrere Keys zu einem Spiel gibt. Der Rekord liegt gerade bei 12 Keys für ein und das selbe Spiel.
