### ISSUE TITLE
Account registrieren funktioniert nicht

### ISSUE THREAD

**Issue by Spirits-** [Deazl/pr0keys#3]
Seite sagt mir dass mein pr0-Account bereits registriert is obwohl ich das nie getan habe, wenn ich versuche mich einzuloggen dass sagt es den Namen gibts in der Datenbank nicht.

**Comment by Deazl** [comment]
@Spirits- Kannst du mir bitte einmal sagen wie du im pr0gramm heißt?

**Comment by stroskler** [comment]
@Spirits- einfach nochmal registrieren hat bei mir auch geklappt habe den gleichen error bekommen

**Comment by Spirits-** [comment]
@Deazl "Spirits" http://pr0gramm.com/user/Spirits

**Comment by ThePhobos** [comment]
Ähnlich bei mir. Wollte mich registrieren (in der 1.0 Version). Dabei trat ein Fehler auf. Neu registrieren geht nicht (Schon vorhanden) und anmelden auch nicht (nicht in der Datenbank) 
Benutzername: Deather

Danke schonmal

**Comment by AtroCty** [comment]
Same here. Username ist gleich.

**Comment by Deazl** [comment]
Nabend ihr drei,

Ich habe eure Accounts gelöscht. Ihr könnt sie nun neu registrieren.

**Comment by DerTuep** [comment]
Habe das selbe Pr0blem 
Usner Name: Kotnascher030

**Comment by antrosyd** [comment]
Hab auch das gleiche Problem
User Name: deLys1d

**Comment by ErenJaeger69** [comment]
Dasselbe Problem, 
ErenJaeger

**Comment by ErenJaeger69** [comment]
Hat sich geklärt, ging jetzt..

**Comment by sl4v3r** [comment]
aaaaaalso, ich habe dir ja schon bei pr0 geschrieben, dass ich auch den Fehler hatte, das mein Account anscheinend schon registiert war.

Dann hast du mir einen Verifizierungs-Key geschickt und es hat alles geklappt.

Dann hast du die Website geschlossen und nach dem sie wieder on war, sollte ich einen neuen verifizierungscode eingeben.
Habe allerdings keinen per email oder bei pr0 als pn bekommen (habe schon einen neuen schicken lassen - immer noch niuchts.)

pr0gramm acc: sl4v3r
pr0key acc: sl4v3r

**Comment by panande** [comment]
Habe ebenfalls den Fehler, dass ich keine Nachricht bekomme.

Accountname ist panande

Danke.

**Comment by MorgenFreimann** [comment]
selbes problem, 
MorgenFreimann

**Comment by JoshuaBehrens** [comment]
selbes Problem. Email kenne er nicht, Passwort wäre inkorrekt. Username mangafreak1995
