### ISSUE TITLE
Name des Einlösers führt zu einem Anderen.

### ISSUE THREAD

**Issue by DanielHopein** [Deazl/pr0keys#30]
Wenn ich Keys geteilt habe sehe ich den Namen des Benutzers, welcher ihn für sich reserviert hat, klicke ich jedoch auf seinen Namen werde ich zum User ,/user/System, weitergeleitet. Der normale Name der Person, welche den Key reserviert hat wird jedoch korrekt angezeigt, weshalb dies keine große Sache, sondern nur ein kleiner Bug ist.

**Comment by Deazl** [comment]
Siehe #21.

Das Update liegt bereits auf dem Server, jedoch habe ich gerade einige Probleme dieses zum laufen zu kriegen. Warum es rum muckt? Keine Ahnung, bin noch am suchen.

**Comment by Deazl** [comment]
Im 1.2.1 Hotfix gefixxt. Ist nun Live!
