### ISSUE TITLE
Vorschlag: Key freigeben

### ISSUE THREAD

**Issue by chill0r** [Deazl/pr0keys#31]
In Verbindung zu #28 wäre noch ein 

> Key freigeben

 hilfreich.
Hiermit könnte man wählen, dass man diesen bzw. einen Key gerade nicht möchte - aber auch keinen neuen angezeigt haben will.

Als Beispiel:
Es sind nur wenige Keys vorhanden und von diesen möchte ich keinen. Aktuell lasse ich einfach einen der angezeigten Keys anstehen - dieser wird jedoch für mich reserviert.
Wenn diese Option vorhanden wäre könnte ich den Key wieder freigeben ohne einen neuen zu erhalten wodurch die Anzahl verfügbarer Keys wieder steigt.

**Comment by chill0r** [comment]
Nvm... Ich hab die bereits geschlossenen beiträge diesbezüglich nicht gesehen...

**Comment by Deazl** [comment]
Da reservierte Keys inzwischen nach ca. 30 Minuten wieder freigegeben werde, ist das nicht notwendig.
