### ISSUE TITLE
Geben und Nehmen?

### ISSUE THREAD

**Issue by neokon** [Deazl/pr0keys#32]
Ich gebe gerne Keys raus hab auch oft mal welche über oder bekomme welche durch Gewinnspiele oder anderes. Jedoch finde ich das Leute die nichts spenden mehr als nur 24 H Pausieren müssten. Oder du machst 2 Tage wo man Keys ziehen kann aber halt nur 1 für jeden und mehr für Leute die welche einstellen. 

Beispiel: Kevin hat kein Geld und will mal wieder was Spielen also guckt er Sa. nach was es für Keys gibt und zack er findet Tetris. Das macht Kevin glücklich und er löst diesen Key ein.

Falk hat durch Pfandflaschen Sammeln richtig Asche gemacht und haut jetzt 6 Keys raus. Dafür bekommt er 6 Keys auf sein Konto die er abholen darf wenn die Müllwagenfahrer schneller sind(Die Ficker). weil er ein Edler Spender ist. Plus den Sa. Key der eh 4 Free ist.

Heißt wer gutes tut bekommt gutes zurück. Sollte dann die Key Zahl natürlich Explodieren so gibt es Free Keys für alle.

Wie du es umsetzt ist mir schlussendlich egal nur Leechen ist egal wie und wo scheiße.

Beste Möglichkeit um Steam Spiele abzufragen ist natürlich wenn es ne Möglichkeit gibt auf den Steamnamen zugreifen zu können so sieht man auch wer welches Spiel DLC etc schon hat.

**Comment by Deazl** [comment]
Wurde hier schon oft genug vorgeschlagen.
