### ISSUE TITLE
Falsches Spiel erhalten

### ISSUE THREAD

**Issue by iAvalon** [Deazl/pr0keys#33]
Angegeben war Company of Heroes. Nachdem ich auf "Key erhalten" gedrückt hatte bekam ich jedoch "RADical ROACH Deluxe Edition".

**Comment by Deazl** [comment]
Kannst du mir bitte die ersten oder die letzten 4 Stellen deines Keys nennen?

**Comment by iAvalon** [comment]
Bh6pt


Sent from my Samsung device

-------- Original message --------

**Comment by Deazl** [comment]
Rückgängig machen kann ich das ganze nicht, da bereits ein anderer den Key erhalten hat.
Wenn du magst, kann ich den Key jedoch zurück in den Pool werfen.

**Comment by iAvalon** [comment]
Wenn du dann meinen Timer zurücksetzt gerne. Sonst behalten ich ihn.

**Comment by Deazl** [comment]
Ja, dadurch wird dein Timer zurückgesetzt, so dass du dir ein neues Spiel holen kannst.

**Comment by iAvalon** [comment]
Na dann los. Vielen Dank!


Sent from my Samsung device

-------- Original message --------

**Comment by Deazl** [comment]
Ist zurückgesetzt.
