### ISSUE TITLE
Fake keys durch regex prüfen

### ISSUE THREAD

**Issue by napstr** [Deazl/pr0keys#34]
Moin,

hab das Teil grade mal ausprobiert, und einen Key erhalten der keiner ist (zumindest funktioniert er nicht bei Steam).
**(zensiert)**

Das ließe sich bei der Eingabe ganz einfach mit einer Regular Expression überprüfen. Das verhindert natürlich keine Trolls, aber wenn sich der Sponsor um ein Zeichen vertippt, beim copypastieren ein Zeichen auf der Strecke bleibt oder Zeichen in den Key geraten die dort nichts zu suchen haben bekommt der Sponsor einen Hinweis darauf. Das würde die Welt für alle schöner machen.

In der Steamproduktaktivierung sind drei Muster angegeben:
http://puu.sh/nbr57/52cac6cb6b.png

Dafür sind hier die jeweiligen Regular Expressions:
(A) /([a-z]|[0-9]){5}-([a-z]|[0-9]){5}-([a-z]|[0-9]){5}/gi
(B) /([a-z]|[0-9]){5}-([a-z]|[0-9]){5}-([a-z]|[0-9]){5}-([a-z]|[0-9]){5}-([a-z]|[0-9]){5}/gi
(C) /[0-9]{3}[a-z]{12}\s[0-9]{2}/gi

Wichtig ist, dass regex (B) auch regex (A) beinhaltet. Es muss also je nach Länge des eingegeben Keys (für (A) 17, für (B) 29, für (C) 18) ein anderer Regex zum Prüfen ausgewählt werden.

**Comment by chill0r** [comment]
Wichtig wäre hierbei aber noch die Auswahl ob es sich um einen Steam, Origin, HumbleBundle o.ä. Key handelt da diese unterschiedliche Kriterien besitzen.

**Comment by napstr** [comment]
Logo. Je nachdem was noch supported werden soll kann das noch mehr werden. Hier ein brauchbares Tools für's regexen: https://regex101.com/

**Comment by chill0r** [comment]
Ich würde die regex aber auf
> ((([a-zA-Z0-9]-?){5}){3})|(([a-zA-Z0-9]-?){5}){5}|([a-zA-Z0-9]{15}\s[a-zA-Z0-9]{2})
vereinfachen um die erkennung zu vereinfachen.

https://regex101.com/r/bJ2sB9/1 (Hint: Die Matcherkennung ist hier nicht ganz richtig bei regex101)

**Comment by Deazl** [comment]
Bitte poste hier keine Keys.

Bei dem Key handelt es sich um einen Uplay Key.
