### ISSUE TITLE
Vorschlag:  Benis

### ISSUE THREAD

**Issue by Alpha63** [Deazl/pr0keys#36]
Mein Vorschlag wäre einen Button zu implementieren der dem spender durch betätigen dieses Buttons ein + Benis erteilt.

Irgendwie will man sich ja bedanken und steigert evtl die motivation mehr Keys zu laden, denn vorher haben die Leute auch Benis damit Farmen können wenn sie es als Bild bei Pr0 hochgeladen hatten. Dies waren meist nur +11.

Wie kann man as Umsetzen?
Man nimmt das letzte Bild aus dem Profil des spenders und kann automatisiert das + drücken lassen.

**Comment by Deazl** [comment]
Wird nicht umgesetzt. Dazu müssen die User ihren pr0gramm Account verlinken. Da es keine OAuth Schnittstelle gibt, müsste ich entweder das Passwort oder den Cookie im Klartext speichern.

Wenn Keys geteilt werden, sollte das getan werden, weil man es möchte und nicht um Benis zu farmen.
Sonst hätte ich diese Plattform gar nicht zu machen brauchen.
