### ISSUE TITLE
Verlinkung der User

### ISSUE THREAD

**Issue by hrkrx** [Deazl/pr0keys#37]
Die verlinkung der User für die ein Key reserviert ist funktioniert gar nicht oder selten, ahbe es mit bei 7 verschiedenen Usern probiert und es hat nur bei einem geklappt. Nämlich nur bei dem ersten Key den ich geteilt habe.

**Comment by Deazl** [comment]
Was genau funktioniert denn nicht? Wie sieht der Link aus?

**Comment by hrkrx** [comment]
Bei allen wo es nicht geht werde ich auf https://pr0gramm.com/user/System verlinkt

**Comment by hrkrx** [comment]
Habe gerade bemerkt, dass es bei allen so ist wo "nur" reserviert steht, die die angenommen haben gehen

**Comment by Deazl** [comment]
Danke für die Meldung des Fehlers. Ich habe den Bug nun behoben.
