### ISSUE TITLE
Werbung schalten

### ISSUE THREAD

**Issue by xlaum** [Deazl/pr0keys#39]
Wärs prinzipiell nicht möglich, dass du werbung auf der seite zeigst, und (fast) jeder adblock ausmacht damit man von den einnahmen paar neue keys kaufen kann? Hätte ja jeder was von.

**Comment by Deazl** [comment]
Ich habe bereits an Werbung gedacht um Keys für die Seite kaufen und auch Events veranstalten zu können, an denen gute User (Also die, die auch viel geben) auch mal was wertvolles zurück bekommen kann.

Da ich grundsätzlich kein Fan von Werbung bin, habe ich erst an ein Spendenmodell gedacht, welches jedoch rechtlich gesehen nicht ganz so einfach umzusetzen ist.

Ich werde schauen in wiefern sich das lohnt, da der Gewinn auch entsprechend sein muss. Sollte ich gerade mal 1€ bis 2€ im Monat dadurch bekomme, würde der damit verbundene Aufwand alles andere als lohnen. Ich entscheide sobald ich ein paar Analytics Auswertungen habe.

**Comment by xlaum** [comment]
Ok, ja wegen paar € würde es sich nicht lohnen, aber bei 2000 nutzern kommt doch bestimmt n bisschen mehr zusammen?

Noch n problem: "ACHTUNG!!! Key für Curse Premium 30 Tage: ****-****-****-**** Curse war nicht in der Auswahl". 
Hab den "key" bekommen, und weiß nicht was ich damit machen soll, da ich ihn keineswegs gebrauchen kann. Angeboten wurde mir Serious Sam: The Random Encounter

**Comment by Deazl** [comment]
Es sind zwar knapp 2000 User registriert, jedoch "nur" 1000 davon aktiviert.
Gut, könnte sich vielleicht doch ein bisschen lohnen. Soweit ich weiß gibts zwischen 12 Cent und 1,20€ für einen Click-per-mile (1000 Impressionen). Ich werde mich mal weiter mit Google AdSense beschäftigen.

**Comment by hrkrx** [comment]
Meiner Erfahrung nach lohnt das kaum, da du damit rechnen musst, dass min. 85% einen Adblocker benutzen und die restlichen 15% einfach zu wenig sind umrelevante einnahmen zu generieren.

**Comment by Deazl** [comment]
Wir? Ist meine seid 5 Jahren die ich für alles benutze ;)

Wie gehabt funktioniert das Werbung schlagen natürlich nur wenn alle bzw. die meisten den AdBlocker aus machen. Wie gesagt: Ich werden mal schauen und dann überlegen.

**Comment by Vaess** [comment]
Eventuell mal mit https://www.patreon.com versuchen?

**Comment by Deazl** [comment]
@Vaess 
Bin bereits auf Patreon, muss die Seite nur mal anpassen :)

**Comment by Deazl** [comment]
Erstmal kein weiteres Statement dazu.
