### ISSUE TITLE
Funktioniert das Key-holen zZt?

### ISSUE THREAD

**Issue by TesTaL0rch** [Deazl/pr0keys#4]
Habe es gerade erfolgreich geschafft mich (erneut) zu verifizieren. Ich erhalte nun die Meldung
"Du kannst dir erst in -1 Stunden wieder einen Key abholen."
Bedeutet dieses "-1", dass ich mir in <1h 'nen neuen key holen könnte? Oder Funktioniert das Ganze gerade (bei mir) nur nicht richtig? 

Ich komme drauf, weil ich mir gestern erfolgreich einen key geholt habe und das war 16:18 Uhr - das bedeutet die 24h wären theoretisch rum. Und ich habe jetzt auch schonmal versuchsweise 20min gewartet. Aber korrigiert mich bitte, falls ich mich irre.

**Comment by Deazl** [comment]
Mir ist der Fehler bekannt, ich konnte ihn selbst jedoch noch nicht reproduzieren.
Kannst du mir sagen ob du auf die Seite http://keys.deazl.com/keys/claim kommst, oder ob du zurück geworfen wirst?

**Comment by TesTaL0rch** [comment]
Werde zurückgeworfen auf [http://keys.deazl.com/](url)

**Comment by Deazl** [comment]
Wir werden uns das so schnell wie möglich ansehen.

**Comment by TesTaL0rch** [comment]
Ok, danke.
Es ist dir vermutlich schon bekannt, aber falls du es noch nicht kennst, das "-1" ist ein Counter - ist bei mir nun auf -2 gesprungen.

**Comment by IXArcanumXI** [comment]
Ähnliches Problem bei mir. Gestern um 18:28 einen Key geholt, jetzt steht dort, dass ich in 0 Stunden einen neuen Key bekommen kann. Werde auch zurückgeworfen auf http://keys.deazl.com/ wenn ich http://keys.deazl.com/keys/claim besuche.

**Comment by xlaum** [comment]
Genau das gleiche Problem bei mir. Username xlaum

**Comment by F4gg0t** [comment]
Selbes Problem hier. Name: Minions

**Comment by hex16de** [comment]
Selbes Problem. Name: HEX16DE

**Comment by Deazl** [comment]
Ich werde mich dem Problem gleich persönlich annehmen.

**Comment by Deazl** [comment]
Das Problem sollte nun gelöst sein.
