### ISSUE TITLE
Einloggen nicht möglich

### ISSUE THREAD

**Issue by 17leo06** [Deazl/pr0keys#41]
Seit einigen Tagen kann ich mich einfach nicht mehr einloggen. Das Passwort wurde am Anfang automatisch gespeichert, jedoch musste ich mich nach dem Reset wieder neu einloggen. Da mein Passwort nicht funktioniert hat und ich es in Erwägung gezogen habe, dass sich schon bei der Registrierung ein Fehler ins Passwort eingeschlichen hat, habe ich jede nur erdenkliche Schreibweise meines PW versucht, aber nichts funktioniert. Ich fände es sehr gut wenn mein Account einfach von der Seite gelöscht wird und ich mich somit erneut registrieren kann.

**Comment by 17leo06** [comment]
http://pr0gramm.com/user/17leo06

**Comment by Deazl** [comment]
Meinst du, es wird dadurch besser, dass du deinen alten Beitrag löscht und einen neuen erstellst? Nein.
Siehe Antwort in Issue #40.
