### ISSUE TITLE
Probleme mit der Zeitanzeige

### ISSUE THREAD

**Issue by pnisi** [Deazl/pr0keys#42]
Eine sehr schöne Sache wäre es, wenn das Zeitsystem überarbeitet wird, ich persönlich fände es besser, wenn man nicht 24h warten müsste, sondern jeden Tag von 0 - 24 Uhr einen Key erhalten kann und wenn man die Frist verpasst, wird halt der Key vom nächsten Tag verwendet. Wenn das abgelehnt wird, sollte aber trotzdem eine Verbesserung vorgenommen werden, die restliche Zeit bis zum nächsten Key sollte immer angezeigt werden und nicht nur, wenn es auch einen Key gibt, der noch nicht reserviert ist. Als letztes noch eine eventuelle Bugmeldung, denn gerade als ich mal schauen wollte, wann meine Zeit vorbei ist, wurde mir angezeigt, dass ich noch 6h warten müsste, also  irgendwann nach um 3.00 Uhr morgen früh wäre das. Ich habe aber zu der Zeit mir keinen Key geholt, sondern irgendwann früher, ich erinnere mich nicht mehr genau an die Zeit, ich bin mir aber ziemlich sicher, dass es noch vor Mitternacht war. 

Edit: habe entdeckt, dass man die Zeit sieht, wenn man auf das Spiel klickt, ich erinnere mich nicht mehr daran, den Key so spät erhalten zu haben, aber das System sagt was anderes: am 20.02.2016 um 02:08 Uhr (18 hours ago), dabei muss ich anmerken, dass das keine 6h sind, die mir noch fehlen, also sollte die Anzeige von der übrigen Zeit etwas genauer, evt. mit Minuten dazu, gemacht werden.

Edit2: habe mich daran erinnert, dass man ja auf Steam seinen Verlauf anschauen kann und da steht die Aktivierung für den 19.2. drin

**Comment by Deazl** [comment]
Wie heißt du im pr0gramm?

**Comment by pnisi** [comment]
imperatortom

**Comment by Deazl** [comment]
Du hast den Key am 20.02 um 02:08:12 Uhr bekommen.

**Comment by pnisi** [comment]
so mal schnell einen Screenshot von meinen Steamlizenzen gemacht, das Spiel, um das es geht ist am 19.2. von mir aktiviert worden. 

![lizenz](https://cloud.githubusercontent.com/assets/17338669/13199216/89db62f4-d81f-11e5-843e-8c28c32e49bc.png)

**Comment by Deazl** [comment]
![yyxkkvv](https://cloud.githubusercontent.com/assets/6287093/13199246/79a90944-d820-11e5-9644-85460c09cdd4.png)

Ich werde da auch keine Ausnahme machen, tut mir leid.

**Comment by pnisi** [comment]
Damit habe ich kein Problem, das war nur als Bugreport von meiner Seite aus gedacht, wenn ich nocheinmal etwas bemerke werde ich mich wieder melden.

**Comment by Deazl** [comment]
Ich bitte darum :).
Vielen Dank!
