### ISSUE TITLE
Key bereits eingelöst 

### ISSUE THREAD

**Issue by tayutayu** [Deazl/pr0keys#44]
will jetzt nicht wie ein Geier erscheinen doch wurde mein Thief Key bereits eingelöst bevor ich es tun konnte :D

kein Plan ob es bei anderen auch schon mal vorgekommen ist

**Comment by Deazl** [comment]
Vorgekommen ist das schon ein paar Mal.
In solchen Fällen bitte immer direkt erstmal an denjenigen wenden, der den Key eingereicht hat. Sollte er sich nicht melden oder dir seine Ausrede nicht gefallen, kannst du dich hier wieder melden.

**Comment by RatihX** [comment]
Moin,

selbes Problem. Es gab anscheinend keinen Tippfehler, da glaube ich OldiMoldi mal:

OldiMoldi  – PRIVATE NACHRICHTEN

hi, soweit ich weiß wurder der von einem anderen user schon benutzt. habe den key abgeglichen. kein fehler drinnen. 

wenn ich einen weiteren habe, kann ich dir den ja zukommen lassen ;) 

lg
OldiMoldi vor einem Moment r antworten
Moin, 

schreibe Dir bzgl. des Keys für Stronghold Kingdoms Island Warfare. 
Laut Steam ist der Schlüssel 337A-8ED3-DBFF-2E67 bereits aktiviert. 

Hast Du eventuell einen Tippfehler gemacht? 

Danke und viele Grüße,
autisteng0re vor 21 Stunden

**Comment by Deazl** [comment]
Hey @RatihX 
Bitte achte darauf hier in Zukunft keine Keys mehr zu posten.
Sofern er dir einen neuen Key zukommen lässt, ist alles in Ordnung.

Da @tayutayu nichts mehr geschrieben hat, gehe ich davon aus, dass sich das Thema erledigt hat.
