### ISSUE TITLE
Reservierter Key verschwunden

### ISSUE THREAD

**Issue by RatihX** [Deazl/pr0keys#45]
Moin,

entweder ich leide an fortgeschrittener geistiger Behinderung, oder die Seite mit dem reservierten Key ist wirklich verschwunden, nachdem ich die Seite gewechselt habe, bzw. auf eine andere Sub-Seite von keys.deazl.com navigiert habe. Habe auch versucht über .../keys/claim auf die Seite zu kommen - erfolglos.

VG,
autisteng0re

**Comment by Deazl** [comment]
Das ist ja mal wirklich autisteng0re...
Wie lautet dein Name auf pr0gramm? Dann schau ich nach und aktiviere den Key fest für deinen Account, sofern dieser noch reserviert ist.

**Comment by Deazl** [comment]
//Anhang: Okey, selber Name macht das ganze ein wenig einfacher. Es handelt sich um das Spiel "Stronghold Kingdoms". Möchtest du das haben? Beachte, dass wenn du dir jetzt einen neuen Key nimmst, ich den Key in den Pool werfe.

**Comment by RatihX** [comment]
Danke für die schnelle Rückmeldung!
Würde gerne Stronghold Kingdoms in Anspruch nehmen.

Habe die anderen vorgeschlagenen Keys declined.

**Comment by Deazl** [comment]
Ich habe dir den Key soeben zugeordnet.

**Comment by RatihX** [comment]
Danke! 

/thread
