### ISSUE TITLE
Keys doppelt vergeben?

### ISSUE THREAD

**Issue by therealshark** [Deazl/pr0keys#48]
Ich habe diesen Key https://deazl.com/keys/45 geteilt. Den Giftinglink habe ich dazu frisch generieren lassen. Nun hat mich allerdings Hanfgranate angeschrieben mit der Nachricht, dass der Link schon benutzt ist. Ich kann mit 100%er Sicherheit sagen, dass der Link funktioniert hat. Kann es sein, dass die Webapp aus unerfindlichen Gründen den Key 2 Leuten zugewiesen hat und der andere glückliche den Key eingelöst hat?

**Comment by Deazl** [comment]
Vielen Dank, Fehler behoben!
