### ISSUE TITLE
Keine eMail erhalten.

### ISSUE THREAD

**Issue by Quadratball** [Deazl/pr0keys#49]
Hallo Menschen,

nachdem ich mich angemeldet habe bekam ich die aufforderung meine eMail-Adresse anzugeben. Habe also eine gmail-Adresse angegeben und leider keine bekommen. Ebenfalls fehlt mir die Möglichkeit eine erneute Mail zu schicken bzw nochmal zu überprüfen ob ich mich eventuell vertippt habe.
Ich bekomme zwar den Hinweis wenn ich mich einloggen will dass ich vor dem Formular die Aktivierungs-Mail erneut verschicken kann allerdings finde ich dazu keine Option.

**Comment by Deazl** [comment]
Hey @Quadratball,
du kannst dir auf der Login Seite nun eine neue Mail zusenden lassen.

**Comment by Quadratball** [comment]
Button nun vorhanden und funktioniert.

**Comment by Deazl** [comment]
Vielen Dank!

**Comment by xpko** [comment]
Seit dem Redesign kann ich mich nicht mehr einloggen eine confirmation-mail kommt auch nicht an.
