### ISSUE TITLE
Freischaltcode ist nicht korrekt

### ISSUE THREAD

**Issue by Skrypto** [Deazl/pr0keys#5]
Moin,
habe mich ganz normal angemeldet und auch einen Freischaltcode per Pr0 Nachricht bekommen. Wenn ich diesen jedoch eingebe kommt die Fehlermeldung:

Der eingegebene Freischaltcode ist nicht korrekt.

**Comment by Deazl** [comment]
Hey @Skrypto,
könntest du den Freischaltcode bitte einmal hier posten?

**Comment by Skrypto** [comment]
cSbQ6yk9cWaQOND8

**Comment by Deazl** [comment]
@Skrypto du bist nun freigeschaltet.

**Comment by Skrypto** [comment]
Danke <3
