### ISSUE TITLE
Page error = Chance vertan

### ISSUE THREAD

**Issue by NekNekx** [Deazl/pr0keys#50]
Wenn ein Page error stattfindet (zb bei klick auf Claim Key) wird der Versuch dennoch gewertet. Somit habe ich gerade einen Key angezeigt bekommen die anderen 2 "refresh" versuch jedoch sind aufgrund eines timeout fehlers verloren gegangen.

**Comment by Deazl** [comment]
Nach mehrfachem Wunsch wurde das Versuchslimit nun entfernt.
