### ISSUE TITLE
Username von Spender nicht verlinkt

### ISSUE THREAD

**Issue by xlaum** [Deazl/pr0keys#51]
Als erstes mal großes Lob an dich, die neue Seite sieht echt gut aus!

Also zu meiner "Anmerkung": Wenn ich auf "Claimed Keys" gehe, seh ich ja von wem der Key ist, aber da ich/wir ja faul sind und nicht extra auf pr0 gehen wollen und /user/... eingeben wollen, wäre eine Verlinkung besser. War ja auch vorher schon vorhanden, also bestimmt nicht schwer das hinzuzufügen. Vielleicht hast dus ja einfach nur vergessen 

Edit: bzw in meinem Fall finde ich den User nicht mal auf pr0

**Comment by Deazl** [comment]
So direkt ist da erstmal nichts geplant.

**Comment by xlaum** [comment]
ähm sorry aber wie soll ich mich dann bedanken?

**Comment by Deazl** [comment]
Entweder gibst du den Namen manuell ein, oder du wartest bis die Profilseite fertig ist.

**Comment by xlaum** [comment]
und wie such ich bitte nach "Moby-Slim" ?

**Comment by Deazl** [comment]
Aktuell gar nicht.
