### ISSUE TITLE
Registrierung

### ISSUE THREAD

**Issue by progamer94** [Deazl/pr0keys#53]
Also ich finde das neue Layout auf jeden Fall ansprechend. Aber kann sich denn nicht jetzt jeder einen Account machen, auch ohne einen Pr0gramm-account? Oder habe ich die verifizierung übersehen?

**Comment by Deazl** [comment]
Ja, es kann sich aktuell jeder einen Account erstellen, auch ohne pr0gramm Account. Eine Verlinkung wird aber wieder hinzukommen.

Jedoch gibts nun den Vorteil, dass man sich keine zig Accounts machen kann um tolle Spiele abzuzwacken. Einerseits können Keys nur einmal eingefügt werden, sprich man kann sich keinen Account machen, sich Keys holen und bei einem anderen wieder teilen. Und andererseits bekommt man nur Noob-Spiele (Billig & schlechte Bewertungen) wenn man keine Keys selbst teilt.

Ich habe vorhin einmal nachgeschaut (Als Vergleich):
Um einen AAA-Titel wie Batman Arkham Knight zu bekommen, ist eine Reputation von 900+ notwendig.
Für ein Spiel wie Flesh Eaters jedoch nur ~14, weshalb diese auf 0 runtergesetzt werden.

**Comment by progamer94** [comment]
ok. das mit der reputation finde ich auch eigentlich eine coole Sache, allerdings finde ich es auf der anderen seite wieder schade, weil viele nutzer halt einfach gerne (gute) keys verschenken, weil sie anderen eine freude machen wollen und nicht weil sie tauschen wollen. weil ich meistens eher klamm bin, werde ich wohl eher weniger keys teilen. und so habe ich dann nichtmal die geringste chance, ein "gutes" Spiel zu bekommen. wenn nutzer auf pr0 teilen, tun sie es ja auch ohne gegenleistung. nur ein Denkanreiz, weil man eigentlich einem geschenkten gaul nicht ins maul schaut, aber ich hoffe du weisst, was ich meine.

**Comment by Deazl** [comment]
Für soetwas habe ich selbstverständlich Verständnis, weshalb es aus (hoffentlich baldigen) Werbeeinnahmen auch Events und die Verlosung von mehreren AAA-Titeln (Auch aktuelle Titel und neue Releases) veranstaltet werden.

Das Teilen von Keys wird nicht die einzige Möglichkeit sein Reputation zu erhalten. Sobald das Forum implementiert ist wirds auch dort die Möglichkeit geben durch z.B. hilfreiche Beiträge (Danksagungen etc.) Reputation zu erhalten. Ebenfalls spiele ich mit dem Gedanken Reputation beim Claimen eines Spieles abzuziehen, so dass die User nicht einfach jedes Spiel nehmen sondern schon mit Bedacht wählen.

**Comment by progamer94** [comment]
Ok, cool. ich finde das echt krass, mit wieviel eifer du an die sache gehst und weiß, wieviel arbeit sowas ist. Auf jeden fall hut ab vor dem portal und deinem support :)
