### ISSUE TITLE
Ein Tag

### ISSUE THREAD

**Issue by thelordhimself** [Deazl/pr0keys#54]
Wie lange genau soll ein Tag sein? denn nachdem der letzte Key schon 27 Stunden her ist, steht immernoch die Meldung da: "Only 1 Key per day"

**Comment by Deazl** [comment]
Update wurde deployed.

**Comment by TesTaL0rch** [comment]
Und das heißt jetzt genau? Funktioniert es erst morgen wieder? Sorry, ich steh da nicht in der Materie..
Bei mir sind's jetzt aber auch schon etwa 28h..

**Comment by Deazl** [comment]
Scheduler läuft aktuell. Die Datum

**Comment by NekNekx** [comment]
Ich bin nun auch über die 24 Stunden hinweg (24 Stunden 20 Minuten) noch gehts nicht

**Comment by thelordhimself** [comment]
update hat scheinbar nix gebracht

**Comment by TesTaL0rch** [comment]
same hier.. das update hat wohl nix geändert. werds morgen nochmal versuchen

**Comment by Deazl** [comment]
Das Update hat einiges geändert.
Jeden Tag um 24 Uhr wird die Zeit zurückgesetzt.

Damit ists nun nicht zwingend auf alle 24 Stunden sondern auf einmal am Tag begrenzt.

**Comment by NekNekx** [comment]
Na die Info wäre vorher praktisch gewesen gut zu wissen also nehme ich an das wir alle um 00:00 die seite wieder nutzen können?

**Comment by Deazl** [comment]
Jup.

**Comment by xlaum** [comment]
ich gebe in 10min bescheid ob es geklappt hat!

**Comment by NbdY83** [comment]
Warte mittlerweile seit vorgestern. Schon sehr ärgerlich wenn man Täglich 3-5 Keys spendet. Design hin oder her, die Seite davor funktionierte besser

**Comment by thelordhimself** [comment]
> Design hin oder her, die Seite davor funktionierte besser

In der Tat mein Freund. Ich fürchte, die Funktionalität ist ein Opfer der Optik geworden

**Comment by xlaum** [comment]
Ach, was einmal ging wird auch irgendwann wieder funktionieren.

**Comment by Deazl** [comment]
Ich hab extra meinen Rechner für euch wieder angemacht und Lost unterbrochen. Gut, lag eher daran, dass Amazon die Serie eben aus Prime raus genommen hat aber gut ;)

**Comment by xlaum** [comment]
Seht her ein gutmensch!

**Comment by NekNekx** [comment]
Zur Info 8 Stunden nach Stunde 0 geht es immernoch nicht ^^ wir könnten natürlich auch nen Venustag einführen (243 Erdtage) ¯\_(ツ)_/¯

**Comment by thelordhimself** [comment]
Vielleicht ist es ja das selbe Problem wie bei der alten Version? Da hatt ichs, dass die Zeit ins Minus lief, aber nichts resettet wurde (also quasi "du kannst erst in -3h einen neuen Key holen")

**Comment by Deazl** [comment]
Hab den Fehler den Morgen noch gefunden, jedoch nicht beheben können. Ich werde mich nun ransetzen.

**Comment by xlaum** [comment]
Bei mir funktionierts jetzt! Danke

**Comment by thelordhimself** [comment]
Obs funktioniert kann ich noch nicht sagen, da ich noch keinen Key geclaimed hab und dann nach 24 Uhr wieder einen bekommen konnte, also wird der endgültige Test noch ein wenig dauern

**Comment by Deazl** [comment]
@thelordhimself Du kannst auch so wieder einen claimen, da ich den Timer für alle wieder auf 0 gesetzt habe. Kulanz aufgrund der Fehler.
