### ISSUE TITLE
Key schon verwendet

### ISSUE THREAD

**Issue by T1biriy** [Deazl/pr0keys#57]
Moin,
habe mir grade einen Key für Life is Hard ergeiert und als Ich ihn einlösen wollte war er schon verwendet.
Bug im System oder hat ihn Keyspender der Hurensohn schon benutzt?

**Comment by Xyotic** [comment]
Hab auch gerade nen gebrauchten key bekommen.
Keyspender der Hurensohn

**Comment by Deazl** [comment]
Nein, beids mein Fehler. Könnt ihr mir bitte jeweils die ersten beiden Blöcke der Keys zukommen lassen?

**Comment by Xyotic** [comment]
H5RIK-YVV58

**Comment by Deazl** [comment]
Du kannst dir nun einen neuen Key holen.

**Comment by Xyotic** [comment]
Danke ^^
Leider sind jetzt schon alle weg...

**Comment by BirdSchiss** [comment]
Selbiges Problem gerade bei: "Lara Croft and the Guardian of Light", der Key ist ungültig!
Key: GYYEC-HJP6G....

**Comment by Deazl** [comment]
@BirdSchiss
Das ist kein migrierter Key und daher nicht mein Fehler. Ich werde schauen was ich tun kann.

**Comment by hrkrx** [comment]
@Deazl, wie wäre es mit nem Reportbutton der auswirkung auf die reputation hat?

**Comment by Deazl** [comment]
Ist in einer lokalen Version schon seit ein paar Updates drin und auch die Datenbankstruktur dafür existiert schon (sogar auf dem Livesystem), jedoch hatte ich ein paar Schwierigkeiten.

**Comment by T1biriy** [comment]
Die ersten beiden Blöcke meines Keys sind KXYAC-CTMFX - danke für den schnellen Support :)

**Comment by Deazl** [comment]
Danke, ich habe den Key aus der Datenbank entfernt.

**Comment by progamer94** [comment]
auch mein key für mini metro funktioniert nicht :( erste beiden blöcke: feg54-hgdhj

**Comment by Deazl** [comment]
Keine Erstattungen mehr. Diese galten nur für von mir migrierte Keys.

**Comment by TesTaL0rch** [comment]
Aber wie ist jetzt das Prozedere, bei ungültigen keys - hat man einfach Pech gehabt? Soll mans einfach ignorieren und die Jungs Reputation farmen lassen? Oder jedes mal hier, in diesen Threat posten (oder einen neuen aufmachen), damit du dem "Spender" manuel Rep wieder abziehst? Oder gibt es eine andere Möglichkeit?

Hatte grad einen ungültigen key für Nail'd (DFMFG-GLFSR)
..bin im Übrigen auch dafür, Leute, die mit ungültigen keys nur Rep sammeln, ganz zu sperren.

**Comment by eltomato89** [comment]
Hatte leider auch grade einen bereits benutzten Key (für > 100 Rep). Schade dass es da keinen Support gibt

**Comment by Deazl** [comment]
Es gibt aktuell keinen Support mehr, da ich derzeit all meine Energie darein stecke herauszufinden wer sich hier unzählige Accounts erstellt. Gestern habe ich 78 Multiaccounts gelöscht, von einem User. Heute sind schon wieder 27 neue da.

**Comment by xlaum** [comment]
Wie kann man nur so ein Geier sein...

Schade trotzdem, dass ich dann wieder mit 0 Credits anfangen muss obwohl man nichts dafür kann.
Wird die Reputation von den anderen in Credits umgewandelt oder fangen die auch bei 0 an?

**Comment by Deazl** [comment]
Die Credits werden neu berechnet und ihr fangt nicht bei 0 an.

**Comment by xlaum** [comment]
Naja ich schon

**Comment by Deazl** [comment]
Wenn du bisher keine Keys geteilt hast, dann ja.

**Comment by xlaum** [comment]
wie gesagt ich habe 5 keys geteilt, einer wurde "gelöscht" und meine 92 reputation hab ich für nen ungültigen key ausgegeben. nice

**Comment by Deazl** [comment]
Die Löschung von Keys wurde nicht beabsichtigt. Gerne kannst du diesen wieder einpflegen, so dass ich diesen wiederum als vergeben markieren kann. Dazu würde ich dich bitten ein weiteres mal in Discord online zu kommen um uns ggf. absprechen zu können.

**Comment by hrkrx** [comment]
Wann kommt denn sowas wie ein Reportbutton? Denn mittlerweile hätte ich den leider auch nötig.

Zur vorgehensweise, wäre ebay als vorbild evtl praktisch:

- nach dem Report wird der user erstmal benachrichtigt und sein claiming/sharing erstmal gesperrt
- nach einer gewissen reaktionszeit wird entweder nichts gemacht oder der shareacc gesperrt und die Rep werden zurückerstattet

**Comment by Deazl** [comment]
Wie gesagt, etwas derartiges ist in Planung. Jedoch stehen aktuell andere Sachen etwas weiter oben auf der ToDo List. Ua. die Sicherheit, Anti-Spam Maßnahmen etc.
