### ISSUE TITLE
Kontaktmöglichkeit / Impressum

### ISSUE THREAD

**Issue by xpko** [Deazl/pr0keys#59]
Es fehlt eine Möglichkeit über die Homepage Kontakt aufzunehmen, z.B. wenn etwas mit dem Login nicht funktioniert.

Auch ein Impressum solltest du dringends hinzufügen, sonst gibts noch Ärger.

**Comment by Deazl** [comment]
Solange ich kein Gewerbe betreibe (was aktuell der Fall ist), werde ich auch kein Impressum einfügen. Gerne darfst du in den WhoIs meiner Domain schauen.

Ein Ticketsystem wirds geben.

**Comment by progamer94** [comment]
Du solltest da eher vorsichtig sein. ich hatte mich mal mit der Impressumspflicht bei blogs beschäftigt und da muss man auch bei nicht kommerziellem gebrauch ein Impressum haben. Soweit ich weiss gilt das für alle seiten, für die man nicht nachweisen kann, dass sie nur für den privaten gebrauch sind, sonst können mitbewerber klagen. wie groß das risiko dabei ist weiß ich auch nicht, solltest aber vorsichtig sein. alle angaben natürlich ohne gewähr

**Comment by xpko** [comment]
Sowas hatte ich nämlich auch im Kopf.

**Comment by Deazl** [comment]
Ich weiß von der Impressumspflicht. Auf all meinen anderen Websites befolge ich diese auch brav.
Lasst das bitte mal meine Sorge sein ;)
