### ISSUE TITLE
Freischaltcode ist nicht korrekt

### ISSUE THREAD

**Issue by Skrypto** [Deazl/pr0keys#6]
Wie in meinem alten thread schon beschrieben habe ich immer noch das gleiche Problem, dass mein Freischaltcode nicht funktioniert. Die Freischaltung vom Admin hat leider auch nicht funktioniert.

**Comment by Deazl** [comment]
Entschuldige, mein Fehler. Nun aber :)

**Comment by Skrypto** [comment]
Sry aber geht immer noch nicht :D

**Comment by Deazl** [comment]
Jetzt sollte es klappen. Das Problem ist, dass wenn Anfragen quasi hängen bleiben, diese manchmal erst später ausgeführt und somit ein neuer Token gesetzt wird.

**Comment by Skrypto** [comment]
klappt leider immer noch nicht :D

**Comment by Deazl** [comment]
Kannst du mir deinen Namen nochmal schreiben?

**Comment by Skrypto** [comment]
Skrypto

**Comment by Deazl** [comment]
Jetzt aber, tut mir leid, die ganze Zeit die falsche ID bearbeitet ;)

**Comment by Skrypto** [comment]
wie viel Benis muss man denn haben um die Seite nutzen zu können?

**Comment by Deazl** [comment]
Du benötigst einen Mindestbenis von 1000, wie auch schon in Ticket #9 beschrieben.
