### ISSUE TITLE
Login für mich nicht möglich/confirmation kommt nicht an

### ISSUE THREAD

**Issue by xpko** [Deazl/pr0keys#61]
Hallo,

seit dem Redesign kann ich mich nicht mehr einloggen und auch eine confirmation-mail kommt auch nicht an ( ja, auch nicht im Spam-Ordner ).
Gibt es eine Möglichkeit das zu beheben?

Danke

**Comment by Deazl** [comment]
Warum kannst du dich denn nicht einloggen? Erscheint eine Meldung?
Kannst du mir die ersten 4 Buchstaben deiner Email Adresse nennen?

**Comment by xpko** [comment]
Ich kann dir auch die ganze geben: simonsek@gmx.de

Mein Passwort ist angeblich falsch. Ich bin mir da selbst nicht so sicher, aber das Passwort zurückzusetzen geht ja leider noch nicht ;-)

**Comment by Deazl** [comment]
Ich werde schauen was ich tun kann.

**Comment by xpko** [comment]
Danke, dass wäre nett.

**Comment by xpko** [comment]
Gibts was neues? Kannst du mein Passwort zurücksetzen?

**Comment by Deazl** [comment]
Oh entschuldige, ich hab dieses Ticket leider komplett vergessen. Wie heißt du im pr0gramm & auf deazl.com?

**Comment by xpko** [comment]
Kein Problem. Ich heiße dort jeweils xpk.

**Comment by Deazl** [comment]
Es gibt bereits einen Account mit der Email Adresse namens "ddddddd"...

**Comment by xpko** [comment]
Oh den habe ich wohl aus verstehen erstellt, als ich testen wollte, ob es an der E-mail-Adresse oder am Nutzernamen lag.

**Comment by Deazl** [comment]
Ich habe dir ein neues Passwort per PN auf pr0gramm zukommen lassen.

**Comment by xpko** [comment]
danke

Am 09.03.2016 um 20:22 schrieb Felix Stieglitz:
> h habe dir ein neues Passwort per PN auf pr0gramm zukommen


---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by Deazl** [comment]
Problem ist mittlerweile gelöst.
