### ISSUE TITLE
Reputation

### ISSUE THREAD

**Issue by SuppenPeter15** [Deazl/pr0keys#62]
Hey, wie wird eigentlich entschieden, wie viel Rep man für ein Spiel braucht?
Habe jetzt schon öfters gesehen, dass man für das gleiche Spiel unterschiedlich hohe Reputation brauchte.

Danke und schönen Tag

**Comment by Deazl** [comment]
Die Reputation setzt sich aus dem Preis und der Bewertung zusammen, die ich von der Steam API bekomme. Außerdem gibts einen Bonus sofern garantiert wird, dass der Key auf jeden Fall noch frei ist.

**Comment by Vaess** [comment]
werden da aktuelle Rabatte rausgerechnet?

**Comment by Deazl** [comment]
Es wird immer nur der Vollpreis verwendet, für den der Titel in den Store gestellt wurde.

**Comment by NbdY83** [comment]
Reputation von 89 auf 61, wie kam es dazu?

**Comment by Deazl** [comment]
Wie heißt dein Account?

**Comment by BoboElHrsn** [comment]
Habe auch ziemlich viel Reputation verloren.
Account: BoboElHurensohn

**Comment by therealshark** [comment]
Ebenso, hat sich circa halbiert: theshark

**Comment by Au36** [comment]
Bei mir von 128 auf 18...
Name: Au

**Comment by NbdY83** [comment]
Account Name "AlterEgo"

Da die funktion noch nicht eingebaut ist oder freigeschaltet, Vielen Dank "BoboElHrsn" für Star Wars X-Wing

**Comment by Roffelchen** [comment]
Bei mir war es nicht ganz so krass, aber immerhin von 256 auf 179.
Name: Roffelchen

**Comment by Deazl** [comment]
Beim Claimen wird die Reputation des Keys von der eigenen abgezogen, damit sich niemand eine Reputation von z.B. 10000 ansammeln und somit permanent nur Tripple-A Titel bekommt.

**Comment by Roffelchen** [comment]
Dann sollte sich aber meiner Meinung nach irgendetwas an der Formel ändern. Habe jetzt für 16 Keys, die ich geshared habe (darunter 3 die 800+ Rep brauchen) nur 4 Keys bekommen mit einem Maximum von 200 Rep. Das kann ja nicht so bleiben.

**Comment by BoboElHrsn** [comment]
Schließe mich da Roffelchen an.
Habe 810 Rep rausgehauen für einen Key, der bereits benutzt war.
Eine doch so große Änderung, dass die Rep nun als Währung benutzt wird, sollte vorher angekündigt werden :/

**Comment by hrkrx** [comment]
Wie wäre es wenn man nochmal rep bekommt, wenn der key vom geclaimten user bestätigt wurde?
