### ISSUE TITLE
Kein Claimen mehr möglich

### ISSUE THREAD

**Issue by evilized84** [Deazl/pr0keys#63]
Moin Moin,

ich bekomme neuerdings folgende Fehlermeldung wenn ich nach Keys für mich schauen möchte:

You have shared 5 Keys but also you've claimed 0 already.
You have to share as minimum keys as you claim.

Seit dem letzten Update scheint er meine Keys nicht mehr anzurechnen.

**Comment by Deazl** [comment]
Ich konnte beim testen einen solchen Fehler nicht feststellen. Ich werde sofort nachschauen!
Wie heißt dein Account?

**Comment by evilized84** [comment]
mein account ist "evilized"

Gern geschehen!
