### ISSUE TITLE
Bedienungsanleitung

### ISSUE THREAD

**Issue by Au36** [Deazl/pr0keys#64]
Da anscheinend viele Sachen passieren, über die nicht informiert wurden z.B Reputation wird wie Währung behandelt, fänd' ich sowas wie ne Art Bedienungsanleitung gut. Was mir auch aufgefallen ist, dass man sich Reputation cheaten kann, indem man einfach ein Spiel auswählt und random nen key reinkloppt. Hab schon 2 ungültige keys gehabt. Das solltebauf jeden Fall noch verbessert.

Edit: Außerdem, gibts sowas wie refreshes, könnte auch mal erklärt werden.

**Comment by Deazl** [comment]
Refreshes gibts schon länger nicht mehr. Wo habe ich denn ein Überbleibsel vergessen?

**Comment by Au36** [comment]
Wenn man auf einen seiner geteilten Keys klickt steht oben bei mir 'you have 2 refreshes left'.

**Comment by Roffelchen** [comment]
Oder Anstatt einer Bedienungsanleitung (oder zusätzlich) ein Changelog. Habe mich nämlich schon gewundert was mit den refreshes passiert ist. Könnte man ja hier im Wiki umsetzen, muss ja nicht zwangsweise auf die Seite

**Comment by xlaum** [comment]
Falls das immer noch so ist, wie Au36 sagt und man sich Reputation ercheatet, indem man absichtlich falsche Keys spendet, dann sollte man gebannt werden.
