### ISSUE TITLE
Abfrage "War der Key gültig?" nach annehmen des Keys.

### ISSUE THREAD

**Issue by eltomato89** [Deazl/pr0keys#67]
Es sollte eine Rückmeldung geben, ob der Key eingelöst werden konnte.

Werden Keys eines Users mehrmals als ungültig gemeldet, könnte dieser einfacher gebannt werden.

**Comment by Deazl** [comment]
Wird es. Genauso wird Reputation in Zukunft auch nur noch dann gutgeschrieben, wenn der Key eingelöst werden konnte.
