### ISSUE TITLE
Shared Keys verschwunden

### ISSUE THREAD

**Issue by evilized84** [Deazl/pr0keys#68]
Moin,

mir ist gerade aufgefallen dass drei Shared Keys von meiner Liste verschwunden sind.
Ich hatte folgendes geshared:

Star Wars Kotor 1
Star Wars Kotor 2
Star Wars Empire at War
Warhammer 40k Dawn of War II
und ein
Company of Heroes Addon

Auf meiner Liste sind Kotor 2 sowie das Addon von Company of Heroes nicht mehr verzeichnet.

An meiner Reputation hat sich nichts geändert - aber die zwei verschwundenen Shares von mir machen mich etwas stutzig.

**Comment by Deazl** [comment]
Leider ist mir beim ersten löschen von Spam Accounts ein Fehler unterlaufen. Gerne kannst du diese wieder hinzufügen damit ich sie wieder als geclaimt markieren kann. Dazu würde ich dich bitten mich in Discord anzuschreiben damit wir uns besser absprechen können: http://discord.gg/0rfn0Shp1RtAmqS2
