### ISSUE TITLE
Vorschlag zum präventiven von Scammern

### ISSUE THREAD

**Issue by Moby-Slim** [Deazl/pr0keys#69]
Okay, nachdem ich das dritte Mal hintereinander mit Steam Keys ins Klo gegriffen hatte und rund 1,4k R in den Sand gesetzt hatte, dachte ich: benutz dein Hirn und denk nach wie man ungültige Keys zurückschrauben/präventiven kann.

Mein Gedanke war dabei, dass man erst Rep. bekommt, wenn der der den Steam/Gift Key eingelöst hatte, so was wie eine Abfrage auf der Claimed keys Seite bekommt ob der Key funktioniert hatte; ja, nein, bereits benutz und ungültig, oder so. Zur Sicherheit doppelte Abfrage, mann kann sich manchmal versehen und das falsche erwischen.

Wenn man angegeben hat das der Steam/Gift Key unbenutzt ist, aber er am Ende ungültig ist, mag es sein bei falscher Eingabe oder Mutwillig, das der ehrliche Mensch selber die Chance hat am Ende noch ein bis drei Mal zu editieren.

Beim unehrlichen Mensch, falls er überhaupt editiert, oder nach dreimaligem korrigieren, das man ihm, nach einer vorgegebenen Zeit oder so, die doppelte Menge Rep abzieht wie der Key Wert war.

Wenn man einen Steam/Gift Key eingibt bei den man sich nicht sicher ist ob man ihn schon verwendet hatte oder nicht, ihn damit auch vermerkt und am Ende sich herausstellt das er schon benutzt wurde, kann man eine Kulanz von der Hälfte der Punkte dafür abziehen, ansonsten beim gültigen Key gibt’s volle Punktzahl, oder die Hälfte. (Edit: Ich hatte nie option 'unsicher' benutzt, ich weiß nicht wie es sonst ist.)

Wenn der Aasgeier keine Punkte bekommt, kann er auch keine Keys bei den Ehrlichen abzocken.

Falls ein nicht funktionierender Key erwischt wurde, sollte man auch die Chance haben gleich dafür einen anderen wählen zu können, anstatt bis 24 Uhr warten zu müssen.

Ich hoffe ich habe nichts vergessen, denn ich habe irgendwie das Gefühl das da eine Floskel ist. Kann ich mir aber auch einbilden.

**Comment by Deazl** [comment]
Hey,

bitte Entschuldige die späte Antwort. Ich habe leider keine Benachrichtigung bekommen.

vielen Dank für den Vorschlag! Im aktuellen Update (Dev-Updates ab und zu hier: https://twitter.com/deazl_) werden die Credits (Reputation wird abgeschafft) erst dann gutgeschrieben, wenn der Key als "funktionierend" markiert wurde. Wird ein Key eine Woche lang nicht bestätigt oder als falsch gemeldet wird, wird dieser automatisch bestätigt.

Sollte ein User auffallen alle Keys negativ zu bewerten, bekommen die User die diesen eingereicht die Credits natürlich dennoch manuell gutgeschrieben. Sollte es ein Problem mit einem Key oder etwas anderem geben, kann man sich natürlich jederzeit über das neue Ticketsystem bei mir melden.
