### ISSUE TITLE
Verschiedene Platformen

### ISSUE THREAD

**Issue by Quadratball** [Deazl/pr0keys#7]
Würde mir ein Dropdown-menu wünschen in dem man zwischen Steam/Uplay/Origin etc. wählen kann.
Der nutzer soll die jeweilige Platform dann auch gleich z.B. als Tag vor dem Spielnamen sehen.
Ich nutze beispielsweise gar kein Origin sodass ich Keys dafür grunsätzlich ablehnen würde, allerdings meine Origin-Keys gerne verschenken würde.

PS: Leider kann ich ebenfalls das Spiel Daed Space 3 nicht auswählen und somit auch keinen Key einreichen.

**Comment by ghacproductions** [comment]
Ist in Planung ;)

**Comment by Blizzer92** [comment]
HAben wir schon in der Planung ;)
