### ISSUE TITLE
allowed email provider?

### ISSUE THREAD

**Issue by husqar** [Deazl/pr0keys#71]
Was soll denn der Mist?

**Comment by Deazl** [comment]
Der "Mist" soll dagegen vorgehen, dass User sich extra Domains mieten nur um sich Spam Accounts registrieren zu können. Gut, das geht auch mit Gmail und Co, ist jedoch nicht ganz so komfortabel, zumal bei Gmail keine Accounts Bot gesteuert angelegt werden können.

**Comment by TobsA13** [comment]
Absoluter Bullshit, kann mich nicht registrieren da ich nur meinen eigene Mailserver betreibe und kein anderen Freemail mehr nutze.

Auch ist die Argumentation Bullshit bezüglich keine Bots. Erstmal extra Geld für ne Domain ausgeben und dann noch den einrichtungs Aufwand betreiben, obwohl ich z.B.: bei Gmail unendlich viele Punkte in meine Adresse machen kann oder mit +irgendwas, ne andere Adresse hab und die Mails noch aufn gleichen Account rauskommen.

**Comment by Deazl** [comment]
@TobsA13 
Wenn du meinst, dass das Bullshit ist, dann ist das schön für dich.
Es ist kein Bullshit. So muss ein Account permanent per Hand angelegt werden was Zeit kostet. Via Bot wurden vorher über 100 Spam Accounts mit Random-Email-Adressen von einer einzigen an diesem Tag gemieteten Domain erstellt. Vermutlich Catch-All. Ich bin mir aktuell noch nicht sicher, wie ich es anders lösen konnte. Aktuell scheints einigermaßen OK zu sein. Mir sind zwar unnormal viele Accounts in den letzten Tagen aufgefallen, jedoch habe ich (noch) nichts ungewöhnliches daran entdeckt. Ich bin jedoch weiter auf der Hut!

Ich bin immer offen für Vorschläge.

**Comment by Deazl** [comment]
Kleine Anmerkung: Der Spamfilter erübrigt sich im Update sowieso teilweise, da man keine Reputation mehr durch Fake Keys erschummeln kann.

**Comment by TobsA13** [comment]
@Deazl Nein es muss eben nicht immer ein Account bei Hand angelegt werden. Weil z. B.: test@gmail.com,  t.e.s.t@gmail.com, test+hackzzz@gmail.com, t.....e...s.....t+2555@gmail.com Alles die gleichen Accounts sind und die Mails alle bei test@gmail.com landen. Wie ne Cache-All.

**Comment by Deazl** [comment]
Wie gesagt: Hat sich nach dem Update sowieso erledigt.
