### ISSUE TITLE
Keine bestätigungs E-Mail

### ISSUE THREAD

**Issue by aceus1** [Deazl/pr0keys#72]
Wie auch schon in der PM auf Pr0 beschrieben, bekomme ich keine Bestätigungsmail, verwendete Domains: "gmx.at" "gmail.com" "hotmail.com", Benutzer registriert: "aceus1" "aceus2" "Beernd". aceus1& aceus2 sind meine Accounts, bitte dann auch um die Löschung von aceus2, jedoch Beernd bin nicht ich.

MfG aceus1

**Comment by buurned** [comment]
Ich bin der Benutzer **Beernd** der sich mit einer **@hotmail.com**-Domain angemeldet hat. Nach ungefähr einer Stunde, trotz versuchter neuerlicher zusendung des Aktivierungs-Link keine E-Mail.

MfG Beernd

**Comment by Deazl** [comment]
Ich habe das Problem gefunden und behoben. Sie hingen in der Warteschleife fest und wurden aus einem mir unbekannten Grund nicht versendet. Ich werde am Problem dran bleiben. Ich habe das Problem nun soweit beheben können, dass ihr Emails welche jetzt angefordert werden wieder versendet werden.

Den Account "aceus2" habe ich gelöscht.

**Comment by aceus1** [comment]
Herzlichen dank, ja ich konnte die Registrierung jetzt problemlos vollenden.
