### ISSUE TITLE
Offline?

### ISSUE THREAD

**Issue by evilized84** [Deazl/pr0keys#73]
Moin,

seit gestern ist kein Login mehr möglich, seit heute gibt es nur noch die Fehlermeldung "Page not found".
Was ist da los? ^^

**Comment by Deazl** [comment]
Nein, die Seite ist natürlich nicht offline. Ich bin mir nicht sicher was aktuell los ist. Ich habe eben weitere Bug Reports erhalten. Ich werde mich sofort drum kümmern.

**Comment by Deazl** [comment]
Problem gelöst. Seite ist wieder wie gewohnt online.
