### ISSUE TITLE
Einloggen

### ISSUE THREAD

**Issue by thelordhimself** [Deazl/pr0keys#74]
Aus irgendeinem Grund frisst er sich beim einloggen.

Geb Usernamen und pw ein, setz das Häkchen bei diesem captcha, dann will er dass ich alle Bilder mit irgendwas auswähl, das tue ich, gibtn grünes Häkchen beim Captcha.

Wie ich dann verfahre (auf Login klicken oder warten), ändert an der Situation nichts, fange wieder bei der Seite "Login" an...

Jetzt, nach mehrmaligem versuchen kommt die Meldung "There was an error with your request. Please send the form again. "... Habs natürlich weiterprobiert, nichts...

**Comment by Deazl** [comment]
Das Problem wurde temporär behoben, so dass das Einloggen wieder möglich ist. Ich habe inzwischen auch die Ursache des Problems gefunden. Ich arbeite aktuell an einer Lösung.

Die Info mit "There was an error with your request" kommt, wenn dein CSRF Token ungültig ist (also nicht mehr existiert, erneuert wurde oder einfach nicht mit dem in der auf dem Server gespeicherten Session übereinstimmt). Einfach die Seite neu laden und es sollte wieder funktionieren.

**Comment by thelordhimself** [comment]
Rückmeldung: hat hingehauen
