### ISSUE TITLE
Login funktioniert nicht

### ISSUE THREAD

**Issue by Hoffensterchen** [Deazl/pr0keys#75]
Hallo,

wenn ich den Login mit meinen Daten fülle und bestätige lande ich wieder auf der Login Seite ohne meine Daten und kann mich somit nicht mehr anmelden. Mein Name auf Dealz und Pr0 ist Hoffensterchen. Ich verwende Chrome.

**Comment by scmbb** [comment]
Habe das Problem auch schon seit gestern mit Firefox.

**Comment by Deazl** [comment]
Anscheeinend hat mein HotFiix das Problem nicht gelöst. ICh werde mich sofort dransetzen.

**Comment by Deazl** [comment]
Funktioniert wieder. Mein HotFix hätte das Problem schon gelöst, nur habe ich wohl vergessen den Auslöser zu entfernen.
