### ISSUE TITLE
Report invalid Key

### ISSUE THREAD

**Issue by NekNekx** [Deazl/pr0keys#76]
Habe nun schon 2 mal das Problem gehabt das Keys nicht gehen da sie entweder "Invalid" oder "Benutzt" sind. Eine Funktion zum melden dieser Keys wäre praktisch

**Comment by Deazl** [comment]
Ist in der aktuellen "Local" Beta schon drin. Daten werden in die Beta nie welche übernommen, wer will kann es aber dennoch ausprobieren: http://test.deazl.com

In der kommenden Version gibts dann auch ein Rate System. Die Credits bekommt man auch erst dann, wenn ein Key als "Funktioniert" bewertet wurde. Anschauen kann man sich das auch dort.

**Comment by NekNekx** [comment]
Ah ok supi :D dann bin ich gespannt auf die nächsten Funktionen. Nunja Assis gibts leider überall aber das neue system wäre dann wirklich besser! 

Danke nochmal für deine Arbeit!
