### ISSUE TITLE
Please ensure that you are a human!/Captcha Problem

### ISSUE THREAD

**Issue by Kotter18** [Deazl/pr0keys#78]
Seit Heute morgen taucht beim einloggen immer diese Nachricht auf: "Please ensure that you are a human!". Gibt es ein Update oder liegt es doch an mir?

**Comment by Deazl** [comment]
Danke fürs melden. Es ist jedoch kein Fehler bei dir oder bei der Website. Alle Server in 3 Rechenzentren bei DigitalOcean können derzeit auf keine einzigen Google Server zugreifen. Seit 2 Tagen sind sie bereits dran das Problem zu lösen. Ich suche noch Möglichkeiten das Captcha dennoch irgendwie zum laufen zu kriegen.

Wie lange DigitalOcean noch braucht, kann ich leider nicht sagen.

**Comment by Kotter18** [comment]
Alles klar. Danke für die Info.

**Comment by Deazl** [comment]
Ich konnte das Problem nun temporär beheben. Der Login ist nun wieder möglich.
