### ISSUE TITLE
Kann keine Keys seit 2 Tagen claimen

### ISSUE THREAD

**Issue by kekidikek** [Deazl/pr0keys#80]
Seit 2 Tagen bekomme ich die Nachricht, dass ich innerhalb von 24 Stunden keinen neuen Key claimen kann. Obwohl ich meinen letzten Key am 2016-03-18 15:13:34 geholt habe.
Name: Minions

**Comment by kekidikek** [comment]
Seit 2 Tagen bekomme ich die Nachricht, dass ich innerhalb von 24 Stunden keinen neuen Key claimen kann. Obwohl ich meinen letzten Key am 2016-03-18 15:13:34 geholt habe.
Name: Minions

**Comment by Deazl** [comment]
Das ist normal, wenn du nicht genug Reputation hast um dir Keys leisten zu können.

**Comment by Kotter18** [comment]
Er meint wohl eher das die Nachricht "You only can claim one key per day." nicht weggeht und er deswegen keine Keys mehr claimen kann. Habe momentan das selbe Problem. Meine 24 Stunden sind um, aber claimen geht nicht. Ausserdem habe ich erst gestern um die 90 Keys geteilt die man für 0 Reputation ergattern kann.

**Comment by Deazl** [comment]
Das ist normal. Keys mit einer Reputation von <100 sind für alle verfügbar. Dennoch bekommst du entsprechende Reputation dafür. Das aktuelle Backend, ums wörtlich zu nehmen einfach im Arsch.
Auf meinem Twitter Account poste ich ab und zu Update Screenshots: https://twitter.com/deazl_

**Comment by Deazl** [comment]
Woups, mein Fehler. Ich dachte dabei an etwas ganz anderes. Der Scheduler läuft nun wieder. In spätestens einer Minute solltet ihr beide wieder Keys claimen können.

**Comment by Kotter18** [comment]
Bei mir gehts wieder. Danke!
