### ISSUE TITLE
Massenkeys

### ISSUE THREAD

**Issue by thelordhimself** [Deazl/pr0keys#81]
Weniger ein Bug oder so, als eher ein Verdacht. Momentan ist die Seite ja überschwemmt mit Keys für das Spiel Enclave, alle von einem Nutzer namens Kotter. Teilweise liegen nichtmal 20 Sekunden zwischen den Einreichzeiten. Da frag ich mich jetzt natürlich, geht das mit rechten Dingen zu? Hat der vielleicht die selben Keys mehrmals geteilt? Oder woher kommen da soviele vom selben Spiel? Auch von Trinium Wars sind einige von ihm drin.

Dieser Verdacht mag sich zwar als unbegründet rausstellen, aber komisch finde ich das schon irgendwie...

**Comment by Deazl** [comment]
Es ist durchaus möglich, dass mehrere Keys des selben Spieles vom selben User eingereicht werden. Besonders solche Spiele wie Enclave werden aktuell haufenweise verteilt. Solange die Keys funktionieren, ist nichts dabei.

**Comment by Kotter18** [comment]
Keine Sorge die Keys funktionieren alle wunderbar. Ich habe einen Kumpel der für eine Seite arbeitet die ab und zu Keys verschenken. Deswegen komme ich manchmal direkt an 20-30 ran.

**Comment by xlaum** [comment]
Kann ich bestätigen, habe 2 funktionierende Keys von kotter bekommen!

**Comment by thelordhimself** [comment]
alles klar, hat mich nur ein wenig verwundert, da dacht ich, ich frag mal nach
