### ISSUE TITLE
Cooldown bei ungültigem Key

### ISSUE THREAD

**Issue by Vaess** [Deazl/pr0keys#84]
Hab nen ungültigen Key gemeldet, Credits erhalten aber jetzt nen Cooldown von 21 Stunden.
Wärs nicht sinnvoller den Cooldown dann zurückzusetzen?

**Comment by Deazl** [comment]
Hey,

entschuldige die späte Antwort. Leider habe ich wenig Zeit gehabt und mich in dieser Zeit auch nur um Bugs & Sicherheitslücken gekümmert. Der Timer wurde bereits wieder entfernt. Dieser war ein ungewolltes erneut rein gepatchtes Überbleibsel aus der alten Version.

Viele Grüße,
Deazl_
