### ISSUE TITLE
Passwort vergessen

### ISSUE THREAD

**Issue by chill0r** [Deazl/pr0keys#85]
Leider habe ich mein Passwort vergessen und eine "Passwort vergessen" Option konnte ich nicht finden...
Benutzername: rm0rf

**Comment by Deazl** [comment]
Hey,

ich hatte in letzter Zeit leider nur relativ wenig Zeit für das Projekt. Und die Zeit die ich hatte habe ich in Bugs & Sicherheitslücken gesteckt.

Besteht das Problem immer noch?

Viele Grüße,
Deazl_

**Comment by Deazl** [comment]
Problem wurde mit dem User privat geklärt.
