### ISSUE TITLE
Doppelpost

### ISSUE THREAD

**Issue by Moby-Slim** [Deazl/pr0keys#86]
Ich hatte vorhin **einen** HumbleBundle Gift Link eingereicht, für Hack 'n' Slash, aber da sind gleich drei Einträge davon, mit derselben Zeit. Dabei hatte ich nur einmal auf 'Weiter' geklickt. Bug?

**Comment by xlaum** [comment]
Hat jetzt nichts damit zu tun, will aber nicht extra n issue hier aufmachen: 

Immer wenn man auf Bezahlbar (https://deazl.com/keys/games?page=1&filter=payable) klickt, kommt: Whoops, looks like something went wrong. Liegt das daran, dass ich atm 0 credits habe, oder bekommt das jeder?

**Comment by Deazl** [comment]
@xlaum 
Dafür sind die Issues da...

@Moby-Slim Ich werde mir das ansehen.

**Comment by Deazl** [comment]
Problem wurde längst behoben.
