### ISSUE TITLE
Keine Bestätigungsmail

### ISSUE THREAD

**Issue by TobsA13** [Deazl/pr0keys#87]
Servus bekomme keine Mail, hab jetzt ~10 Stunden gewartet. Accounts: TobsA, TobsA13.  TobsA13 kann gelöscht werden.

Gruß

**Comment by Deazl** [comment]
In Zukunft bitte einfach keine Multiaccounts erstellen. Wie schon öfter gesagt werden aktuell nur die wenigsten Mails versendet. Ich steh bereits mit Mailgun in Kontakt um das Problem zu lösen.

**Comment by ripper121** [comment]
selbes Problem.
Account: ripper121

**Comment by TobsA13** [comment]
Würde mich jetzt schon mal interessieren wie du das Problem lösen willst. Noch 10 Jahre warten? Anderen Anbieter nutzen? Die betroffenen Accounts manuell bestätigen? Vielleicht mal einen Text bei der Registrierung einfügen das man momentan keine Mails bekommt und nicht sagen ist allgemein bekannt (woher auch)?

**Comment by Deazl** [comment]
Viel mehr als zu warten kann ich nicht. Temporär einen anderen Anbieter zu implementieren ist dabei zu viel Aufwand nur um es danach wieder rückgängig zu machen.

Ich werde schauen wie ich das Problem sonst lösen könnte. Undzwar so schnell wie möglich.

**Comment by TobsA13** [comment]
Eigenen Mailserver nutzt ihn ja sowieso nur zum versenden. Sowas ist doch schnell eingerichtet und du bist nicht auf externe Anbieter angewiesen.

**Comment by Deazl** [comment]
Ich werde demnächst einen Mailserver einrichten, welcher auch zum empfangen gedacht ist. Das werde ich nicht mal eben Husch Husch machen.

Wie gesagt, ich werde mich so schnell wie möglich nach Alternativen umsehen. 
Welche Accounts von dir soll ich löschen und welcher soll behalten werden?

**Comment by TobsA13** [comment]
Ok.

TobsA13 löschen und TobsA behalten.

**Comment by Deazl** [comment]
Ist erledigt. Ebenfalls habe ich auf der Registrierungsseite einen kleinen Hinweis untergebracht, wie vorgeschlagen.

**Comment by Deazl** [comment]
Problem ist mittlerweile gelöst.

**Comment by TobsA13** [comment]
Nicht gelöst. Keine Mail bekommen und aktiviert ist mein Account auch nicht.

**Comment by Deazl** [comment]
@TobsA13 Ich habe die E-Mail noch einmal verschicken lassen. Anscheinend wurde deine E-Mail abgearbeitet bevor der Fehler behoben wurde und somit nicht erneut an den Server gesendet.

Ich habe das ganze auch nachgeprüft: Die E-Mail wurde von laut angaben von deinem E-Mail Server akzeptiert und zugestellt.

**Comment by TobsA13** [comment]
Jo kam an danke

Am 2. April 2016 12:29:27 MESZ, schrieb Felix Stieglitz <notifications@github.com>:
>@TobsA13 Ich habe die E-Mail noch einmal verschicken lassen.
>Anscheinend wurde deine E-Mail abgearbeitet bevor der Fehler behoben
>wurde und somit nicht erneut an den Server gesendet.
>
>Ich habe das ganze auch nachgeprüft: Die E-Mail wurde von laut angaben
>von deinem E-Mail Server akzeptiert und zugestellt.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Deazl/pr0keys/issues/87#issuecomment-204690434

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
