### ISSUE TITLE
Whoops, looks like something went wrong

### ISSUE THREAD

**Issue by xlaum** [Deazl/pr0keys#89]
Immer wenn man auf Bezahlbar (https://deazl.com/keys/games?page=1&filter=payable) klickt, kommt: Whoops, looks like something went wrong. Liegt das daran, dass ich atm 0 credits habe, oder bekommt das jeder?

**Comment by scmbb** [comment]
Ist bei mir auch so und ich habe mehr als 0 :D

**Comment by Deazl** [comment]
Nach einigem hin und her konnte ich das Problem nun endlich lösen.
