### ISSUE TITLE
Frage zu Credits bei Humblebundle

### ISSUE THREAD

**Issue by xlaum** [Deazl/pr0keys#90]
Wie werden die Credits berechnet, wenn man ein Humblebundle spendet? 

Edit: Habs gefunden.
Da das HumbleBundle keine Möglichkeit bietet den Wert eines Keys zu prüfen können für jeden eingereichten Geschenk-Link nur 5 Credits gutgeschrieben werden. In den meisten Fällen ist es effektiver den Key anzeigen zu lassen und den Steam-Key direkt einzutragen.

**Comment by Deazl** [comment]
Gar nicht. Steht beim einreichen aber auch drüber. Ich habe keine Möglichkeit zu prüfen wie viel Wert das jeweilige Bundle ist oder wie viel der User dafür gezahlt hat. Aus diesem Grund gibt es für alle HumbleBundle Gifts nur 5 Credits.

**Comment by xlaum** [comment]
Ok danke
