### ISSUE TITLE
Steamaccount verbinden geht nicht

### ISSUE THREAD

**Issue by RavenZero** [Deazl/pr0keys#91]
Nachdem ich mich bei Steam eingeloggt habe werde ich zurück zu deazl geleitet und bekomme die Meldung "Whoops, looks like something went wrong."

**Comment by Deazl** [comment]
Hey,
danke für den Report!

Mir wurde das Problem bereits gemeldet. Ich weiß auch grob was das Problem ist, jedoch hängt die Ursache mit Steam selbst zusammen. Könntest du mir bitte deinen Steam Account (Den Link zum Profil) zukommen lassen damit ich prüfen kann, warum die Kopplung ausgerechnet mit deinem Account nicht funktioniert?

**Comment by RavenZero** [comment]
http://steamcommunity.com/profiles/76561198056534710/
Kann es daran liegen dass mein Profil privat ist?

**Comment by Deazl** [comment]
Das werden wir gleich mal herausfinden.

**Comment by MalaFide** [comment]
Hatte das selbe Problem.
Musste mein Steam Account auf öffentlich stellen, dann gings.
Muss ich das nun auf öffentlich lassen?

**Comment by Deazl** [comment]
Jup, da lag auch genau das Problem. Warum auch immer das Anmeldedatum nicht sichtbar ist, wenn das Profil auf privat gestellt ist. Just Valve things.

Du musst es nicht auf öffentlich gestellt lassen, nein.

**Comment by RavenZero** [comment]
Okay, hat jetzt geklappt mit öffentlichen Profil.
Danke :)

**Comment by Deazl** [comment]
Ich werde dennoch eine weitere Info implementieren um andere User in Zukunft darauf hinzuweisen :)
