### ISSUE TITLE
1 Humblebunde geshared, 3 aufgelistet

### ISSUE THREAD

**Issue by xlaum** [Deazl/pr0keys#93]
Ich hab ein humble bunde geshared, aber es war 3 mal auf der frontpage:
https://i.gyazo.com/0f0470cca23dd8ebd42577fced0e62f9.png

Irgendwas hat da nicht richtig funktioniert, ich hab auch schon 1x5$ gutgeschrieben bekommen, jetzt sind noch 2 weitere gelistet mit "garantiert unbenutzt" aber natürlich sind sie das jetzt nicht mehr, nachdem der erste den giftkey benutzt hat

**Comment by Moby-Slim** [comment]
Ich hatte dasselbe Problem bei Hack 'n' Slash für Humble Bundle: https://github.com/Deazl/pr0keys/issues/86

Mittlerweile wurde einer der drei als schon benutzt gekennzeichnet, seltsamerweise von derselben Person die zwei geclaimt hatte, mit 2 Minuten unterschied. Der dritte ist noch nicht verteilt. Ich habe bis jetzt keine weiteren Humble Bundle Gift links verteilt. Ich will nicht das man mir vorwirft ich täte es mit Absicht.

Bei Steam Codes scheint es jedoch zu funzen.

**Comment by xlaum** [comment]
Ja ich würde auch noch weitere spenden, aber ich warte erstmal auf ne Rückmeldung von deazl

**Comment by Deazl** [comment]
Auf keinen Fall wird niemand für doppelte HumbleBundle Keys gesperrt, nachdem das bekannt geworden ist, da macht euch keine Sorgen.

Ich werde mir das umgehend anschauen und tun was ich kann. Ich bitte darum erstmal keine HumbleBundle Keys mehr einzureichen.

Bei Steam Codes funktioniert das ganze hervorragend wie @Moby-Slim auch schon festgestellt hat.
Woher das Problem kommt kann ich mir momentan nicht erklären.

**Comment by xlaum** [comment]
Ok, danke. Kannst du hier evtl posten wenn man wieder humble bundles spenden kann?

**Comment by Deazl** [comment]
Aber selbstverständlich.

**Comment by Deazl** [comment]
Problem ist nun behoben. Beim erneuten testen konnten keine derartigen Fehler festgestellt werden. Ebenfalls habe ich vorgesorgt, falls erneut ein Problem dieser Art auftreten sollte.

Die doppelten Gifts sollten in den nächsten Minuten aus der Datenbank verschwinden.

**Comment by xlaum** [comment]
Das glaube ich kaum

**Comment by NbdY83** [comment]
Problem besteht immernoch. eben gerade wieder mit Batman und Tropico 5. Wegen Batman der Bereits eingelöst ist wurde mir dank des neuen Systems einfach mal die Hälfte der Credits abgezwackt. Thumbs Up

**Comment by xlaum** [comment]
naja, hätte man sich aber auch denken können

**Comment by xlaum** [comment]
Funktioniert jetzt.

**Comment by Deazl** [comment]
Das Problem wurde schon behoben, nur habe ich vergessen den Dienst neu zu starten, welcher die Jobs cached und ausführt.
