### ISSUE TITLE
Battlepaths wird nicht gefunden

### ISSUE THREAD

**Issue by Cheatyx** [Deazl/pr0keys#94]
Ich habe Battlepaths (key 2843) eingestellt, dies kann aber nicht über die suche gefunden werden, auch in der Liste nicht vorhanden

**Comment by Deazl** [comment]
Der Key wurde eingetragen. Du kannst nur nicht deine eigenen Keys sehen :)

**Comment by Cheatyx** [comment]
Achso, aber Speile wo andere auch einen EIntrag haben kann ich sehen...
