### ISSUE TITLE
Danke für Minus

### ISSUE THREAD

**Issue by NbdY83** [Deazl/pr0keys#99]
Danke für die Unterstellung das ich irgendwelche Bugs ausgenutzt hätte. Habe deine miserabel gecodete Scheiß Seite genutzt wie du sie hingeschissen hast. 45 geteilte Keys und nur 22 in Anspruch genommen.
Bekomm deinen Scheiß in den Griff bevor du Ehrlichen Usern derartige Dinge unterstellst. Ist eine Frechheit, aber nicht das erste mal das ich um meine Credits beschissen wurde. Alles was damit zutun hat ist auf deinem Mist gewachsen!

**Comment by Deazl** [comment]
Ich unterstelle in erster Linie niemandem etwas. Ich werde zu dem ganzen Projekt und dem aktuellen Scheiß den ich verzapfe in sehr naher Zukunft ein offizielles Statement abgeben. Ich kann die Unmut gut verstehen die aktuell rumgeht.

Wie lautet der Name deines Accounts auf deazl.com? Gerne schaue ich mir deinen Fall einmal genauer an.

**Comment by Deazl** [comment]
Kleiner Edit: Aufgrund des Reports und nach einer kurzen Prüfung wird provisorisch ein Dump der Usertabelle von vor etwa 15 bis 20 Minuten eingespielt, bevor die Credits neu berechnet wurden. Somit sind alle wieder bei ihrem Stand.

**Comment by Pandiora** [comment]
@NbdY83 Meine Güte, du bist hier nicht auf pr0, also pass mal deinen Tonfall an. Keiner zwingt dich die Seite zu nutzen und solange du keine bessere Alternative lieferst, würde ich an deiner Stelle Stillschweigen bewahren.
